import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const sidebarLeftComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "250px",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 10px",
      boxShadow: "2px 0 5px rgba(0,0,0,0.1)",
    },
    tailwindStyles: "flex flex-col items-start w-40 h-full p-4 bg-white shadow-md transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "Dashboard",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "20px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-5 text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Analytics",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Reports",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "280px",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 15px",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-full p-6 bg-gray-900 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "ADMIN PANEL",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "30px",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-white text-lg font-bold mb-8 tracking-wide text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
          backgroundColor: "#393e46",
        },
        tailwindStyles: "w-full text-white my-3 py-2 px-4 bg-gray-800 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Users",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#d1d1d1",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
        },
        tailwindStyles: "w-full text-gray-300 my-3 py-2 px-4 hover:bg-gray-800 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#d1d1d1",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
        },
        tailwindStyles: "w-full text-gray-300 my-3 py-2 px-4 hover:bg-gray-800 rounded text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "240px",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 12px",
      borderRight: "1px solid #e0e0e0",
    },
    tailwindStyles: "flex flex-col items-start w-60 h-full p-5 bg-gray-100 border-r border-gray-200 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "Menu",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#6c757d",
          fontSize: "14px",
          fontWeight: "500",
          marginBottom: "15px",
          textTransform: "uppercase",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-gray-500 text-sm font-medium mb-4 uppercase tracking-wide text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Products",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Orders",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "260px",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "30px 15px",
      borderRight: "1px solid #eaeaea",
    },
    tailwindStyles: "flex flex-col items-center w-64 h-full p-7 bg-white border-r border-gray-100 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "BRAND",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "22px",
          fontWeight: "bold",
          marginBottom: "40px",
          letterSpacing: "2px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-10 tracking-wider text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50 text-sm md:text-base sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Profile",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50 text-sm md:text-base sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50 text-sm md:text-base sm:px-2",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};