import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const sidebarRightComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "300px",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 15px",
      boxShadow: "-2px 0 5px rgba(0,0,0,0.1)",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-full p-5 bg-white shadow-md fixed right-0 top-0 md:w-56 sm:w-40 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "Notifications",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "20px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-5 text-center md:text-lg sm:text-sm",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NotificationItem",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "12px",
          borderBottom: "1px solid #eee",
          display: "flex",
          flexDirection: "column",
        },
        tailwindStyles: "w-full p-3 border-b border-gray-100 flex flex-col text-sm md:text-xs sm:text-[10px]",
        elements: [
          {
            type: "Text",
            content: "New message received",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-gray-800 text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "5 minutes ago",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#888",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-500 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarRightComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "320px",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 15px",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-80 h-full p-6 bg-gray-900 fixed right-0 top-0 md:w-60 sm:w-40 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "ACTIVITY FEED",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "30px",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-white text-lg font-bold mb-8 tracking-wide text-center md:text-base sm:text-sm",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ActivityItem",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "15px",
          backgroundColor: "#393e46",
          borderRadius: "8px",
          marginBottom: "15px",
          display: "flex",
          flexDirection: "column",
        },
        tailwindStyles: "w-full p-4 bg-gray-800 rounded-lg mb-4 flex flex-col text-sm md:text-xs sm:text-[10px]",
        elements: [
          {
            type: "Text",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-white text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "5 minutes ago",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#aaa",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-400 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarRightComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "280px",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 15px",
      borderLeft: "1px solid #e0e0e0",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-full p-5 bg-gray-100 border-l border-gray-200 fixed right-0 top-0 md:w-56 sm:w-40 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "Recent Updates",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#343a40",
          fontSize: "18px",
          fontWeight: "600",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-lg font-semibold mb-5 text-center md:text-base sm:text-sm",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "UpdateItem",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "12px",
          backgroundColor: "white",
          borderRadius: "6px",
          marginBottom: "12px",
          display: "flex",
          flexDirection: "column",
          boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
        },
        tailwindStyles: "w-full p-3 bg-white rounded-md mb-3 flex flex-col shadow-sm text-sm md:text-xs sm:text-[10px]",
        elements: [
          {
            type: "Text",
            content: "Product Update v2.1",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-gray-800 text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#6c757d",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-600 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarRightComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "330px",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 20px",
      boxShadow: "-2px 0 10px rgba(0,0,0,0.05)",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-80 h-full p-6 bg-white shadow-md fixed right-0 top-0 md:w-64 sm:w-48 transition-all hidden sm:block",
    elements: [
      {
        type: "Text",
        content: "People Online",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-lg font-bold mb-5 text-center md:text-left sm:text-sm",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "UserItem",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "10px 0",
          borderBottom: "1px solid #f0f0f0",
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyles: "w-full py-2 border-b border-gray-100 flex flex-row items-center text-sm md:text-base",
        elements: [
          {
            type: "Text",
            content: "•",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#4CAF50",
              fontSize: "24px",
              marginRight: "10px",
            },
            tailwindStyles: "text-green-500 text-2xl mr-2",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
            },
            tailwindStyles: "text-gray-800 text-md",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};