import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const sidebarLeftComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "260px",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      padding: "24px 16px",
      boxShadow: "0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)",
      transition: "all 0.3s ease",
    },
    tailwindStyles:
      "flex flex-col justify-between h-full bg-white shadow-xs border-r border-gray-100 w-full md:w-64 sm:w-20 p-4 sm:p-2 md:p-6 transition-all duration-300",
    elements: [
      // Top section with logo and navigation
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          width: "100%",
          gap: "24px",
        },
        tailwindStyles: "flex flex-col w-full gap-6",
        elements: [
          // Logo section
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              marginBottom: "16px",
              paddingBottom: "16px",
              borderBottom: "1px solid #f1f1f1",
            },
            tailwindStyles:
              "flex items-center mb-4 pb-4 border-b border-gray-100",
            elements: [
              {
                type: "Text",
                content: "DASHBOARD",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#111827",
                  fontSize: "18px",
                  fontWeight: "600",
                  letterSpacing: "0.5px",
                },
                tailwindStyles:
                  "text-gray-900 text-lg font-semibold tracking-wide sm:hidden",
              },
            ],
          },

          // Navigation section
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              width: "100%",
              gap: "4px",
            },
            tailwindStyles: "flex flex-col w-full gap-1",
            elements: [
              // Navigation header
              {
                type: "Text",
                content: "MENU",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#6B7280",
                  fontSize: "12px",
                  fontWeight: "500",
                  marginBottom: "8px",
                  letterSpacing: "0.8px",
                  textTransform: "uppercase",
                },
                tailwindStyles:
                  "text-gray-500 text-xs font-medium mb-2 tracking-wide uppercase sm:hidden",
              },

              // Home link - active state
              {
                type: "Link",
                content: "Home",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4F46E5",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  backgroundColor: "#EEF2FF",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-indigo-600 bg-indigo-50 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-indigo-100",
                href: "/",
              },

              // Analytics link
              {
                type: "Link",
                content: "Analytics",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-gray-50",
                href: "/analytics",
              },

              // Reports link
              {
                type: "Link",
                content: "Reports",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-gray-50",
                href: "/reports",
              },

              // Settings link
              {
                type: "Link",
                content: "Settings",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-gray-50",
                href: "/settings",
              },
            ],
          },

          // Secondary Navigation
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              width: "100%",
              gap: "4px",
              marginTop: "24px",
            },
            tailwindStyles: "flex flex-col w-full gap-1 mt-6",
            elements: [
              // Secondary header
              {
                type: "Text",
                content: "WORKSPACE",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#6B7280",
                  fontSize: "12px",
                  fontWeight: "500",
                  marginBottom: "8px",
                  letterSpacing: "0.8px",
                  textTransform: "uppercase",
                },
                tailwindStyles:
                  "text-gray-500 text-xs font-medium mb-2 tracking-wide uppercase sm:hidden",
              },

              // Projects link
              {
                type: "Link",
                content: "Projects",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-gray-50",
                href: "/projects",
              },

              // Team link
              {
                type: "Link",
                content: "Team",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                },
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center gap-3 hover:bg-gray-50",
                href: "/team",
              },
              {
                type: "Button",
                name: "Dropdown Menu",
                buttonType: "multi",
                content: "More Options",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                tailwindStyles:
                  "w-full text-gray-600 my-0.5 py-2.5 px-3 rounded-md font-medium flex items-center justify-between gap-3 hover:bg-gray-50",
                styles: {
                  color: "#4B5563",
                  margin: "2px 0",
                  fontSize: "14px",
                  fontWeight: "500",
                  width: "100%",
                  padding: "10px 12px",
                  borderRadius: "6px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  cursor: "pointer",
                  transition: "background-color 0.2s",
                  border: "none",
                  backgroundColor: "transparent",
                },
                element: {
                  type: "Frame",
                  name: "Dropdown Content",
                  id: uuidv4(),
                  content: "",
                  styles: {
                    display: "none",
                    flexDirection: "column",
                    width: "100%",
                    backgroundColor: "#ffffff",
                    border: "1px solid #f1f1f1",
                    borderRadius: "6px",
                    boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
                    padding: "4px",
                    gap: "2px",
                    overflow: "hidden",
                    marginTop: "8px",
                  },
                  elements: [
                    {
                      type: "Button",
                      id: uuidv4(),
                      content: "Profile Settings",
                      isSelected: false,
                      x: 0,
                      y: 0,
                      buttonType: "primary",
                      styles: {
                        padding: "8px 12px",
                        width: "100%",
                        textAlign: "left",
                        backgroundColor: "transparent",
                        color: "#374151",
                        border: "none",
                        borderRadius: "4px",
                        cursor: "pointer",
                        fontSize: "14px",
                        transition: "background-color 0.2s",
                      },
                      tailwindStyles:
                        "text-gray-700 hover:bg-gray-100 rounded w-full text-left px-3 py-2 text-sm",
                    },
                    {
                      type: "Button",
                      id: uuidv4(),
                      content: "Notifications",
                      isSelected: false,
                      x: 0,
                      y: 0,
                      buttonType: "primary",
                      styles: {
                        padding: "8px 12px",
                        width: "100%",
                        textAlign: "left",
                        backgroundColor: "transparent",
                        color: "#374151",
                        border: "none",
                        borderRadius: "4px",
                        cursor: "pointer",
                        fontSize: "14px",
                        transition: "background-color 0.2s",
                      },
                      tailwindStyles:
                        "text-gray-700 hover:bg-gray-100 rounded w-full text-left px-3 py-2 text-sm",
                    },
                    {
                      type: "Button",
                      id: uuidv4(),
                      content: "Advanced Options",
                      isSelected: false,
                      x: 0,
                      y: 0,
                      buttonType: "primary",
                      styles: {
                        padding: "8px 12px",
                        width: "100%",
                        textAlign: "left",
                        backgroundColor: "transparent",
                        color: "#000000",
                        border: "none",
                        borderRadius: "4px",
                        cursor: "pointer",
                        fontSize: "14px",
                        transition: "background-color 0.2s",
                      },
                      tailwindStyles:
                        "text-white hover:bg-gray-700 rounded w-full text-left px-3 py-2 text-sm",
                    },
                  ],
                  isSelected: false,
                  x: 0,
                  y: 0,
                },
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
      },

      // Bottom section for user profile
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          alignItems: "center",
          padding: "12px",
          marginTop: "auto",
          borderRadius: "8px",
        },
        tailwindStyles:
          "flex items-center p-3 mt-auto rounded-lg gap-3",
        elements: [
          // User text
          {
            type: "Text",
            content: "John Doe",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              fontSize: "14px",
              fontWeight: "500",
            },
            tailwindStyles: "text-white text-sm font-medium sm:hidden",
          },
        ],
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "280px",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 15px",
      gap: "16px",
    },
    tailwindStyles:
      "flex flex-col items-start h-full bg-gray-900 w-full md:w-64 sm:w-20 p-4 sm:p-2 md:p-6 gap-4 sm:gap-6 transition-all duration-300",
    elements: [
      {
        type: "Text",
        content: "ADMIN PANEL",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "30px",
          letterSpacing: "1px",
        },
        tailwindStyles:
          "text-white text-lg font-bold mb-8 tracking-wide text-center md:text-left sm:mb-4 sm:text-base",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          width: "100%",
          gap: "12px",
        },
        tailwindStyles: "flex flex-col w-full gap-3",
        elements: [
          {
            type: "Link",
            content: "Dashboard",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "12px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 15px",
              borderRadius: "5px",
              backgroundColor: "#393e46",
            },
            tailwindStyles:
              "w-full text-white my-2 py-2 px-4 bg-gray-800 rounded flex items-center justify-start md:text-left sm:text-sm sm:px-2 sm:py-1",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Users",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#d1d1d1",
              margin: "12px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 15px",
              borderRadius: "5px",
            },
            tailwindStyles:
              "w-full text-gray-300 my-2 py-2 px-4 hover:bg-gray-800 rounded flex items-center justify-start md:text-left sm:text-sm sm:px-2 sm:py-1",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Settings",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#d1d1d1",
              margin: "12px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 15px",
              borderRadius: "5px",
            },
            tailwindStyles:
              "w-full text-gray-300 my-2 py-2 px-4 hover:bg-gray-800 rounded flex items-center justify-start md:text-left sm:text-sm sm:px-2 sm:py-1",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Button",
            name: "Dropdown Menu",
            buttonType: "multi",
            content: "Advanced Options",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            tailwindStyles:
              "w-full text-gray-300 my-2 py-2 px-4 hover:bg-gray-800 rounded flex items-center justify-between md:text-left sm:text-sm sm:px-2 sm:py-1",
            styles: {
              color: "#d1d1d1",
              margin: "12px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 15px",
              borderRadius: "5px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              cursor: "pointer",
              transition: "background-color 0.2s",
              border: "none",
              backgroundColor: "transparent",
            },
            element: {
              type: "Frame",
              name: "Dropdown Content",
              id: uuidv4(),
              content: "",
              styles: {
                display: "none",
                flexDirection: "column",
                width: "100%",
                backgroundColor: "#2d3239",
                border: "1px solid #393e46",
                borderRadius: "5px",
                boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
                padding: "4px",
                gap: "2px",
                overflow: "hidden",
                marginTop: "8px",
              },
              elements: [
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "Account Settings",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#000000",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-white hover:bg-gray-700 rounded w-full text-left px-3 py-2 text-sm",
                },
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "User Permissions",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#000000",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-white hover:bg-gray-700 rounded w-full text-left px-3 py-2 text-sm",
                },
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "System Configuration",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#000000",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-white hover:bg-gray-700 rounded w-full text-left px-3 py-2 text-sm",
                },
              ],
              isSelected: false,
              x: 0,
              y: 0,
            },
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          marginTop: "auto",
          width: "100%",
          padding: "12px 0",
        },
        tailwindStyles: "w-full mt-auto pt-4 text-white gap-4 sm:gap-2",
        elements: [],
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "280px",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 12px",
      borderRight: "1px solid #e0e0e0",
    },
    tailwindStyles:
      "flex flex-col items-start h-full bg-gray-100 border-r border-gray-200 w-full md:w-64 sm:w-20 p-4 sm:p-2 md:p-5 transition-all duration-300",
    elements: [
      {
        type: "Text",
        content: "Menu",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#6c757d",
          fontSize: "14px",
          fontWeight: "500",
          marginBottom: "15px",
          textTransform: "uppercase",
          letterSpacing: "1px",
        },
        tailwindStyles:
          "text-gray-500 text-sm font-medium mb-4 uppercase tracking-wide text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          width: "100%",
          gap: "12px",
        },
        tailwindStyles: "flex flex-col w-full gap-3",
        elements: [
          {
            type: "Link",
            content: "Home",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#495057",
              margin: "8px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 12px",
              borderRadius: "6px",
              transition: "all 0.2s ease",
            },
            tailwindStyles:
              "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Products",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#495057",
              margin: "8px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 12px",
              borderRadius: "6px",
              transition: "all 0.2s ease",
            },
            tailwindStyles:
              "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Orders",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#495057",
              margin: "8px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 12px",
              borderRadius: "6px",
              transition: "all 0.2s ease",
            },
            tailwindStyles:
              "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Button",
            name: "Dropdown Menu",
            buttonType: "multi",
            content: "More Options",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            tailwindStyles:
              "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600 text-center md:text-left sm:text-sm sm:px-2 flex items-center justify-between",
            styles: {
              color: "#495057",
              margin: "8px 0",
              fontSize: "16px",
              width: "100%",
              padding: "10px 12px",
              borderRadius: "6px",
              transition: "all 0.2s ease",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              cursor: "pointer",
              border: "none",
              backgroundColor: "transparent",
            },
            element: {
              type: "Frame",
              name: "Dropdown Content",
              id: uuidv4(),
              content: "",
              styles: {
                display: "none",
                flexDirection: "column",
                width: "100%",
                backgroundColor: "#f0f7ff", // Changed from #ffffff to light blue
                border: "1px solid #cde1ff", // Changed border color to match the blue theme
                borderRadius: "6px",
                boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
                padding: "4px",
                gap: "2px",
                overflow: "hidden",
                marginTop: "8px",
              },
              elements: [
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "Customer Support",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#495057",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-gray-700 hover:bg-blue-50 hover:text-blue-600 rounded w-full text-left px-3 py-2 text-sm",
                },
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "Reports",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#495057",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-gray-700 hover:bg-blue-50 hover:text-blue-600 rounded w-full text-left px-3 py-2 text-sm",
                },
                {
                  type: "Button",
                  id: uuidv4(),
                  content: "Inventory",
                  isSelected: false,
                  x: 0,
                  y: 0,
                  buttonType: "primary",
                  styles: {
                    padding: "8px 12px",
                    width: "100%",
                    textAlign: "left",
                    backgroundColor: "transparent",
                    color: "#495057",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontSize: "14px",
                    transition: "background-color 0.2s",
                  },
                  tailwindStyles:
                    "text-gray-700 hover:bg-blue-50 hover:text-blue-600 rounded w-full text-left px-3 py-2 text-sm",
                },
              ],
              isSelected: false,
              x: 0,
              y: 0,
            },
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          marginTop: "auto",
          width: "100%",
          padding: "12px 0",
        },
        tailwindStyles: "w-full mt-auto pt-4 gap-4 sm:gap-2",
        elements: [],
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const sidebarLeftComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100%",
      width: "300px",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "30px 20px",
      borderRight: "1px solid #eaeaea",
    },
    tailwindStyles:
      "hidden sm:flex flex-col items-center h-full bg-white border-r border-gray-100 w-full md:w-64 sm:w-20 p-4 sm:p-3 md:p-8 transition-all duration-300",
    elements: [
      {
        type: "Text",
        content: "BRAND",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "22px",
          fontWeight: "bold",
          marginBottom: "40px",
          letterSpacing: "2px",
        },
        tailwindStyles:
          "text-gray-800 text-xl font-bold mb-10 tracking-wider text-center md:text-left",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          width: "100%",
          gap: "12px",
        },
        tailwindStyles: "flex flex-col w-full gap-3",
        elements: [
          {
            type: "Link",
            content: "Dashboard",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#555",
              margin: "10px 0",
              fontSize: "16px",
              width: "100%",
              padding: "12px 15px",
              textAlign: "center",
              borderRadius: "8px",
            },
            tailwindStyles:
              "w-full text-gray-600 my-2 py-3 px-4 rounded-lg hover:bg-gray-50 text-center md:text-center sm:text-sm sm:py-2 sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Profile",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#555",
              margin: "10px 0",
              fontSize: "16px",
              width: "100%",
              padding: "12px 15px",
              textAlign: "center",
              borderRadius: "8px",
            },
            tailwindStyles:
              "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50 text-sm md:text-base sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Settings",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#555",
              margin: "10px 0",
              fontSize: "16px",
              width: "100%",
              padding: "12px 15px",
              textAlign: "center",
              borderRadius: "8px",
            },
            tailwindStyles:
              "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50 text-sm md:text-base sm:px-2",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          marginTop: "auto",
          width: "100%",
          padding: "12px 0",
        },
        tailwindStyles: "w-full mt-auto pt-4 gap-4 sm:gap-2",
        elements: [],
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};
