import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

// Basic Bar Chart Component
export const barChartComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "ChartBar",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "800px",
      height: "400px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      padding: "20px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    tailwindStyles: "w-full max-w-4xl h-96 md:h-96 sm:h-80 bg-white rounded-xl p-5 sm:p-3 shadow-md flex flex-col gap-4",
    elements: [
      {
        type: "Text",
        content: "Sales Performance by Quarter",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "20px",
          fontWeight: "bold",
          color: "#333",
          marginBottom: "10px",
        },
        tailwindStyles: "text-xl font-bold text-gray-800 mb-2.5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ChartContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          flex: "1",
          display: "flex",
          alignItems: "flex-end",
          gap: "16px",
          padding: "20px 40px 20px 40px",
          position: "relative",
        },
        tailwindStyles: "flex-1 flex items-end gap-4 md:gap-4 sm:gap-2 p-5 px-10 sm:px-6 sm:py-3 relative",
        elements: [
          // Y-axis labels
          {
            type: "Frame",
            name: "YAxisLabels",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              position: "absolute",
              left: "0",
              top: "0",
              bottom: "25px",
              width: "40px",
              display: "flex",
              flexDirection: "column-reverse",
              justifyContent: "space-between",
            },
            tailwindStyles: "absolute left-0 top-0 bottom-6 w-10 sm:w-6 flex flex-col-reverse justify-between",
            elements: [
              {
                type: "Text",
                content: "0",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "25",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "50",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "75",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "100",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          // Bar 1
          {
            type: "Frame",
            name: "Bar1",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              flex: "1",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex-1 flex flex-col items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "BarValue",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "70%",
                  backgroundColor: "#4f46e5",
                  borderRadius: "4px 4px 0 0",
                  transition: "height 0.3s ease",
                },
                tailwindStyles: "w-full h-[70%] bg-indigo-600 rounded-t transition-all duration-300 hover:bg-indigo-500",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Q1",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          // Bar 2
          {
            type: "Frame",
            name: "Bar2",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              flex: "1",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex-1 flex flex-col items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "BarValue",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "85%",
                  backgroundColor: "#4f46e5",
                  borderRadius: "4px 4px 0 0",
                  transition: "height 0.3s ease",
                },
                tailwindStyles: "w-full h-[85%] bg-indigo-600 rounded-t transition-all duration-300 hover:bg-indigo-500",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Q2",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          // Bar 3
          {
            type: "Frame",
            name: "Bar3",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              flex: "1",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex-1 flex flex-col items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "BarValue",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "50%",
                  backgroundColor: "#4f46e5",
                  borderRadius: "4px 4px 0 0",
                  transition: "height 0.3s ease",
                },
                tailwindStyles: "w-full h-[50%] bg-indigo-600 rounded-t transition-all duration-300 hover:bg-indigo-500",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Q3",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          // Bar 4
          {
            type: "Frame",
            name: "Bar4",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              flex: "1",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex-1 flex flex-col items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "BarValue",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "65%",
                  backgroundColor: "#4f46e5",
                  borderRadius: "4px 4px 0 0",
                  transition: "height 0.3s ease",
                },
                tailwindStyles: "w-full h-[65%] bg-indigo-600 rounded-t transition-all duration-300 hover:bg-indigo-500",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Q4",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Revenue in millions ($)",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "14px",
          color: "#666",
          textAlign: "center",
        },
        tailwindStyles: "text-sm text-gray-600 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Pie Chart Component
export const pieChartComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "ChartPie",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "500px",
      height: "400px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      padding: "20px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    tailwindStyles: "w-full max-w-xl h-96 md:h-96 sm:h-80 bg-white rounded-xl p-5 sm:p-3 shadow-md flex flex-col gap-4",
    elements: [
      {
        type: "Text",
        content: "Market Segmentation",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "20px",
          fontWeight: "bold",
          color: "#333",
          marginBottom: "10px",
        },
        tailwindStyles: "text-xl font-bold text-gray-800 mb-2.5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ChartContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flex: "1",
          justifyContent: "center",
          alignItems: "center",
        },
        tailwindStyles: "flex-1 flex justify-center items-center",
        elements: [
          {
            type: "Frame",
            name: "PieCircle",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "200px",
              height: "200px",
              borderRadius: "50%",
              background: "conic-gradient(#4f46e5 0% 40%, #06b6d4 40% 65%, #10b981 65% 85%, #6366f1 85% 100%)",
              position: "relative",
            },
            tailwindStyles: "w-52 h-52 md:w-52 md:h-52 sm:w-40 sm:h-40 rounded-full relative bg-gradient-conic from-indigo-600 from-0% via-cyan-600 via-40% via-green-500 via-65% to-indigo-400 to-85%",
            elements: [],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "Legend",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "center",
          gap: "16px",
          marginTop: "20px",
        },
        tailwindStyles: "flex justify-center gap-4 mt-5 flex-wrap",
        elements: [
          {
            type: "Frame",
            name: "LegendItem1",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "ColorIndicator",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "12px",
                  height: "12px",
                  backgroundColor: "#4f46e5",
                  borderRadius: "2px",
                },
                tailwindStyles: "w-3 h-3 bg-indigo-600 rounded-sm",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Enterprise (40%)",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "LegendItem2",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "ColorIndicator",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "12px",
                  height: "12px",
                  backgroundColor: "#06b6d4",
                  borderRadius: "2px",
                },
                tailwindStyles: "w-3 h-3 bg-cyan-600 rounded-sm",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "SMB (25%)",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "LegendItem3",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "ColorIndicator",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "12px",
                  height: "12px",
                  backgroundColor: "#10b981",
                  borderRadius: "2px",
                },
                tailwindStyles: "w-3 h-3 bg-green-500 rounded-sm",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Retail (20%)",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "LegendItem4",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex items-center gap-2",
            elements: [
              {
                type: "Frame",
                name: "ColorIndicator",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "12px",
                  height: "12px",
                  backgroundColor: "#6366f1",
                  borderRadius: "2px",
                },
                tailwindStyles: "w-3 h-3 bg-indigo-400 rounded-sm",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Other (15%)",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "14px", color: "#333" },
                tailwindStyles: "text-sm text-gray-800",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Line Chart Component
export const lineChartComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "ChartLine",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "800px",
      height: "400px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      padding: "20px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    tailwindStyles: "w-full max-w-4xl h-96 md:h-96 sm:h-80 bg-white rounded-xl p-5 sm:p-3 shadow-md flex flex-col gap-4",
    elements: [
      {
        type: "Text",
        content: "User Growth Trends",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "20px",
          fontWeight: "bold",
          color: "#333",
          marginBottom: "10px",
        },
        tailwindStyles: "text-xl font-bold text-gray-800 mb-2.5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ChartContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          flex: "1",
          display: "flex",
          alignItems: "center",
          position: "relative",
          padding: "20px 40px 20px 40px",
        },
        tailwindStyles: "flex-1 flex items-center p-5 px-10 sm:px-6 sm:py-3 relative",
        elements: [
          // Y-axis labels
          {
            type: "Frame",
            name: "YAxisLabels",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              position: "absolute",
              left: "0",
              top: "0",
              bottom: "0",
              width: "40px",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
            },
            tailwindStyles: "absolute left-0 top-0 bottom-0 w-10 flex flex-col justify-between",
            elements: [
              {
                type: "Text",
                content: "100K",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "75K",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "50K",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "25K",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "0",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: { fontSize: "12px", color: "#666" },
                tailwindStyles: "text-xs text-gray-600",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          // Line graph (simplified representation)
          {
            type: "Frame",
            name: "Graph",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              position: "relative",
              flex: "1",
              height: "100%",
              borderLeft: "1px dashed #e5e7eb",
              borderBottom: "1px dashed #e5e7eb",
            },
            tailwindStyles: "relative flex-1 h-full border-l border-b border-dashed border-gray-200",
            elements: [
              // Chart lines representation using SVG-like styling with divs
              {
                type: "Frame",
                name: "LineGraph",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "absolute",
                  width: "100%",
                  height: "100%",
                  top: "0",
                  left: "0",
                  background: "linear-gradient(transparent 60%, rgba(79, 70, 229, 0.1))",
                  borderTop: "3px solid #4f46e5",
                  borderRadius: "2px",
                },
                tailwindStyles: "absolute w-full h-full top-0 left-0 bg-gradient-to-b from-transparent from-60% to-indigo-600/10 border-t-2 border-indigo-600 rounded",
                elements: [
                  // Data points
                  {
                    type: "Frame",
                    name: "DataPoint1",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      left: "10%",
                      bottom: "20%",
                      width: "8px",
                      height: "8px",
                      backgroundColor: "#4f46e5",
                      borderRadius: "50%",
                      transform: "translate(-50%, 50%)",
                    },
                    tailwindStyles: "absolute left-[10%] bottom-[20%] w-2 h-2 bg-indigo-600 rounded-full -translate-x-1/2 translate-y-1/2",
                    elements: [],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "DataPoint2",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      left: "30%",
                      bottom: "40%",
                      width: "8px",
                      height: "8px",
                      backgroundColor: "#4f46e5",
                      borderRadius: "50%",
                      transform: "translate(-50%, 50%)",
                    },
                    tailwindStyles: "absolute left-[30%] bottom-[40%] w-2 h-2 bg-indigo-600 rounded-full -translate-x-1/2 translate-y-1/2",
                    elements: [],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "DataPoint3",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      left: "50%",
                      bottom: "60%",
                      width: "8px",
                      height: "8px",
                      backgroundColor: "#4f46e5",
                      borderRadius: "50%",
                      transform: "translate(-50%, 50%)",
                    },
                    tailwindStyles: "absolute left-[50%] bottom-[60%] w-2 h-2 bg-indigo-600 rounded-full -translate-x-1/2 translate-y-1/2",
                    elements: [],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "DataPoint4",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      left: "70%",
                      bottom: "70%",
                      width: "8px",
                      height: "8px",
                      backgroundColor: "#4f46e5",
                      borderRadius: "50%",
                      transform: "translate(-50%, 50%)",
                    },
                    tailwindStyles: "absolute left-[70%] bottom-[70%] w-2 h-2 bg-indigo-600 rounded-full -translate-x-1/2 translate-y-1/2",
                    elements: [],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "DataPoint5",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      left: "90%",
                      bottom: "85%",
                      width: "8px",
                      height: "8px",
                      backgroundColor: "#4f46e5",
                      borderRadius: "50%",
                      transform: "translate(-50%, 50%)",
                    },
                    tailwindStyles: "absolute left-[90%] bottom-[85%] w-2 h-2 bg-indigo-600 rounded-full -translate-x-1/2 translate-y-1/2",
                    elements: [],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "XAxis",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "space-between",
          padding: "0 40px 0 40px",
        },
        tailwindStyles: "flex justify-between px-10 sm:px-6",
        elements: [
          {
            type: "Text",
            content: "Jan",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: { fontSize: "12px", color: "#666" },
            tailwindStyles: "text-xs text-gray-600",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Mar",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: { fontSize: "12px", color: "#666" },
            tailwindStyles: "text-xs text-gray-600",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "May",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: { fontSize: "12px", color: "#666" },
            tailwindStyles: "text-xs text-gray-600",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Jul",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: { fontSize: "12px", color: "#666" },
            tailwindStyles: "text-xs text-gray-600",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Sep",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: { fontSize: "12px", color: "#666" },
            tailwindStyles: "text-xs text-gray-600",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};
