import { v4 as uuidv4 } from "uuid";
import { CustomComponent } from "../styleconstants";

export const landingPageTemplateComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "LandingPageTemplate",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
    },
    tailwindStyles: "w-full min-h-screen flex flex-col bg-white",
    elements: [
      {
        type: "Frame",
        name: "NavbarSection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          height: "auto",
          minHeight: "70px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "15px 30px",
          backgroundColor: "white",
          boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
          zIndex: "10",
        },
        tailwindStyles: "w-full py-4 px-6 md:px-8 flex flex-col md:flex-row items-center justify-between bg-white shadow-sm sticky top-0 z-10 gap-4 md:gap-0",
        elements: [
          {
            type: "Image",
            content: "Logo",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100px",
              height: "40px",
              objectFit: "contain",
              backgroundColor: "white",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              padding: "8px",
              borderRadius: "4px",
            },
            tailwindStyles: "w-24 h-10 object-contain bg-white flex items-center justify-center p-2 rounded",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "NavLinks",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              gap: "20px",
              alignItems: "center",
            },
            tailwindStyles: "flex flex-wrap md:flex-nowrap items-center gap-3 md:gap-5",
            elements: [
              {
                type: "Link",
                content: "Home",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#333333",
                  fontWeight: "500",
                },
                tailwindStyles: "text-gray-800 font-medium hover:text-sky-500 transition-colors",
                href: "/",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Features",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#333333",
                  fontWeight: "500",
                },
                tailwindStyles: "text-gray-800 font-medium hover:text-sky-500 transition-colors",
                href: "#features",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Pricing",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#333333",
                  fontWeight: "500",
                },
                tailwindStyles: "text-gray-800 font-medium hover:text-sky-500 transition-colors",
                href: "/pricing",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "About",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#333333",
                  fontWeight: "500",
                },
                tailwindStyles: "text-gray-800 font-medium hover:text-sky-500 transition-colors",
                href: "/about",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Button",
                content: "Get Started",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                buttonType: "button",
                styles: {
                  backgroundColor: "#0ea5e9",
                  color: "white",
                  fontWeight: "500",
                  padding: "8px 16px",
                  borderRadius: "6px",
                  border: "none",
                  cursor: "pointer",
                },
                tailwindStyles: "bg-sky-500 text-white font-medium px-4 py-2 rounded-md hover:bg-sky-600 transition-colors",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      
      {
        type: "Frame",
        name: "HeroSection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          minHeight: "600px",
          backgroundColor: "#f0f9ff",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "60px 20px",
        },
        tailwindStyles: "w-full min-h-[600px] bg-sky-50 flex items-center justify-center py-16 px-4 md:px-8",
        elements: [
          {
            type: "Frame",
            name: "HeroContent",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              textAlign: "center",
              maxWidth: "1200px",
              width: "100%",
              gap: "24px",
            },
            tailwindStyles: "flex flex-row items-center justify-between gap-10 md:gap-16 w-full max-w-6xl mx-auto",
            elements: [
              {
                type: "Frame",
                name: "HeroText",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "column",
                  gap: "16px",
                  textAlign: "left",
                  maxWidth: "600px",
                },
                tailwindStyles: "flex flex-col gap-4 text-left w-1/2",
                elements: [
                  {
                    type: "Text",
                    content: "Build your website visually without code",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "40px",
                      fontWeight: "bold",
                      color: "#111827",
                      lineHeight: "1.2",
                    },
                    tailwindStyles: "text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 leading-tight",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Our drag-and-drop web builder makes creating professional websites easy and enjoyable. Get started in minutes, no coding required.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "18px",
                      color: "#4b5563",
                      lineHeight: "1.6",
                    },
                    tailwindStyles: "text-base md:text-lg text-gray-600 leading-relaxed mt-2",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Button",
                    content: "Start Building Now",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    buttonType: "button",
                    styles: {
                      backgroundColor: "#0ea5e9",
                      color: "white",
                      fontWeight: "600",
                      padding: "12px 24px",
                      borderRadius: "8px",
                      border: "none",
                      cursor: "pointer",
                      fontSize: "16px",
                      marginTop: "12px",
                    },
                    tailwindStyles: "bg-sky-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-sky-600 transition-colors text-base md:text-lg mt-4 md:mt-6 self-start",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Image",
                content: "Hero Image",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  maxWidth: "500px",
                  borderRadius: "12px",
                  boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
                },
                tailwindStyles: "w-1/2 max-w-[500px] rounded-xl shadow-xl",
                href: "",
                src: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },      
      {
        type: "Frame",
        name: "FeaturesSection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "80px 20px",
          backgroundColor: "white",
        },
        tailwindStyles: "w-full py-20 px-4 md:px-8 bg-white",
        elements: [
          {
            type: "Frame",
            name: "FeaturesContainer",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              maxWidth: "1200px",
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              gap: "60px",
            },
            tailwindStyles: "max-w-6xl mx-auto flex flex-col gap-16",
            elements: [
              {
                type: "Frame",
                name: "FeaturesHeader",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  textAlign: "center",
                  marginBottom: "20px",
                },
                tailwindStyles: "text-center mb-10",
                elements: [
                  {
                    type: "Text",
                    content: "Key Features",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#0ea5e9",
                      fontWeight: "600",
                      fontSize: "16px",
                      textTransform: "uppercase",
                      letterSpacing: "1px",
                    },
                    tailwindStyles: "text-sky-500 font-semibold text-sm uppercase tracking-wider",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Why Choose Our Platform",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "36px",
                      fontWeight: "bold",
                      color: "#111827",
                      marginTop: "8px",
                    },
                    tailwindStyles: "text-3xl md:text-4xl font-bold text-gray-900 mt-2",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Our platform offers everything you need to build beautiful, functional websites with ease.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "18px",
                      color: "#4b5563",
                      maxWidth: "600px",
                      margin: "16px auto 0",
                    },
                    tailwindStyles: "text-lg text-gray-600 max-w-xl mx-auto mt-4",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "FeaturesGrid",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "grid",
                  gridTemplateColumns: "repeat(3, 1fr)",
                  gap: "30px",
                },
                tailwindStyles: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8",
                elements: [
                  {
                    type: "Frame",
                    name: "FeatureCard1",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "16px",
                      padding: "30px",
                      borderRadius: "8px",
                      backgroundColor: "#f9fafb",
                      transition: "transform 0.3s ease, box-shadow 0.3s ease",
                    },
                    tailwindStyles: "flex flex-col gap-4 p-6 rounded-lg bg-gray-50 hover:shadow-md hover:-translate-y-1 transition-all",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "24px",
                          color: "#0ea5e9",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-sky-500 text-2xl font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Drag & Drop Builder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Build your website visually with our intuitive drag and drop interface. No coding required.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#4b5563",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-base text-gray-600 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureCard2",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "16px",
                      padding: "30px",
                      borderRadius: "8px",
                      backgroundColor: "#f9fafb",
                      transition: "transform 0.3s ease, box-shadow 0.3s ease",
                    },
                    tailwindStyles: "flex flex-col gap-4 p-6 rounded-lg bg-gray-50 hover:shadow-md hover:-translate-y-1 transition-all",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "24px",
                          color: "#0ea5e9",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-sky-500 text-2xl font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Responsive Design",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "All websites are fully responsive, ensuring they look great on any device, from desktop to mobile.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#4b5563",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-base text-gray-600 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureCard3",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "16px",
                      padding: "30px",
                      borderRadius: "8px",
                      backgroundColor: "#f9fafb",
                      transition: "transform 0.3s ease, box-shadow 0.3s ease",
                    },
                    tailwindStyles: "flex flex-col gap-4 p-6 rounded-lg bg-gray-50 hover:shadow-md hover:-translate-y-1 transition-all",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "24px",
                          color: "#0ea5e9",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-sky-500 text-2xl font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Ready-made Templates",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Start with professionally designed templates or build from scratch - the choice is yours.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#4b5563",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-base text-gray-600 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      
      {
        type: "Frame",
        name: "AboutSection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "80px 20px",
          backgroundColor: "#f8fafc",
        },
        tailwindStyles: "w-full py-20 px-4 md:px-8 bg-slate-50",
        elements: [
          {
            type: "Frame",
            name: "AboutContainer",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              maxWidth: "1200px",
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              gap: "60px",
            },
            tailwindStyles: "max-w-6xl mx-auto flex flex-col gap-16",
            elements: [
              {
                type: "Frame",
                name: "AboutHeader",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  textAlign: "center",
                  marginBottom: "40px",
                },
                tailwindStyles: "text-center mb-14",
                elements: [
                  {
                    type: "Text",
                    content: "About Us",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#0ea5e9",
                      fontWeight: "600",
                      fontSize: "16px",
                      textTransform: "uppercase",
                      letterSpacing: "1px",
                    },
                    tailwindStyles: "text-sky-500 font-semibold text-sm uppercase tracking-wider",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Meet the Team Behind the Platform",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "36px",
                      fontWeight: "bold",
                      color: "#111827",
                      marginTop: "8px",
                    },
                    tailwindStyles: "text-3xl md:text-4xl font-bold text-gray-900 mt-2",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "We're a passionate team of designers, developers, and innovators dedicated to making website creation accessible to everyone.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "18px",
                      color: "#4b5563",
                      maxWidth: "700px",
                      margin: "16px auto 0",
                    },
                    tailwindStyles: "text-lg text-gray-600 max-w-2xl mx-auto mt-4",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "TeamProfiles",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "grid",
                  gridTemplateColumns: "repeat(4, 1fr)",
                  gap: "30px",
                },
                tailwindStyles: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8",
                elements: [
                  {
                    type: "Frame",
                    name: "TeamMember1",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      gap: "16px",
                      textAlign: "center",
                    },
                    tailwindStyles: "flex flex-col items-center gap-4 text-center",
                    elements: [
                      {
                        type: "Image",
                        content: "Team Member 1",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "150px",
                          height: "150px",
                          borderRadius: "9999px",
                          objectFit: "cover",
                          border: "4px solid white",
                          boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                        },
                        tailwindStyles: "w-36 h-36 rounded-full object-cover border-4 border-white shadow-md",
                        href: "",
                        src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Sarah Johnson",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "CEO & Founder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#0ea5e9",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-sky-500 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "10+ years of experience in web development and product management.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#6b7280",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-sm text-gray-500 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "TeamMember2",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      gap: "16px",
                      textAlign: "center",
                    },
                    tailwindStyles: "flex flex-col items-center gap-4 text-center",
                    elements: [
                      {
                        type: "Image",
                        content: "Team Member 2",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "150px",
                          height: "150px",
                          borderRadius: "9999px",
                          objectFit: "cover",
                          border: "4px solid white",
                          boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                        },
                        tailwindStyles: "w-36 h-36 rounded-full object-cover border-4 border-white shadow-md",
                        href: "",
                        src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "David Chen",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Lead Developer",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#0ea5e9",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-sky-500 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Expert in frontend frameworks with a passion for creating intuitive user experiences.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#6b7280",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-sm text-gray-500 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "TeamMember3",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      gap: "16px",
                      textAlign: "center",
                    },
                    tailwindStyles: "flex flex-col items-center gap-4 text-center",
                    elements: [
                      {
                        type: "Image",
                        content: "Team Member 3",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "150px",
                          height: "150px",
                          borderRadius: "9999px",
                          objectFit: "cover",
                          border: "4px solid white",
                          boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                        },
                        tailwindStyles: "w-36 h-36 rounded-full object-cover border-4 border-white shadow-md",
                        href: "",
                        src: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Michelle Taylor",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "UI/UX Designer",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#0ea5e9",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-sky-500 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Creates beautiful, functional designs that make our platform a joy to use.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#6b7280",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-sm text-gray-500 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "TeamMember4",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      gap: "16px",
                      textAlign: "center",
                    },
                    tailwindStyles: "flex flex-col items-center gap-4 text-center",
                    elements: [
                      {
                        type: "Image",
                        content: "Team Member 4",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "150px",
                          height: "150px",
                          borderRadius: "9999px",
                          objectFit: "cover",
                          border: "4px solid white",
                          boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                        },
                        tailwindStyles: "w-36 h-36 rounded-full object-cover border-4 border-white shadow-md",
                        href: "",
                        src: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Robert Wilson",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "20px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-xl font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Customer Success",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#0ea5e9",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-sky-500 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Dedicated to ensuring our customers get the most out of our platform.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#6b7280",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-sm text-gray-500 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "CompanyStory",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "column",
                  gap: "20px",
                  marginTop: "60px",
                  backgroundColor: "white",
                  padding: "40px",
                  borderRadius: "12px",
                  boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
                },
                tailwindStyles: "flex flex-col gap-6 mt-16 bg-white p-8 rounded-xl shadow-sm",
                elements: [
                  {
                    type: "Text",
                    content: "Our Story",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "24px",
                      fontWeight: "600",
                      color: "#111827",
                    },
                    tailwindStyles: "text-2xl font-semibold text-gray-900",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "WebBuilder was founded in 2020 with a simple mission: to make web development accessible to everyone. We believe that creating a professional online presence shouldn't require technical expertise or a large budget.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "16px",
                      color: "#4b5563",
                      lineHeight: "1.7",
                    },
                    tailwindStyles: "text-base text-gray-600 leading-relaxed",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "What started as a small project has grown into a full-featured platform used by thousands of individuals and businesses worldwide. Our team has expanded, but our mission remains the same: empowering people to bring their ideas to life on the web.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "16px",
                      color: "#4b5563",
                      lineHeight: "1.7",
                    },
                    tailwindStyles: "text-base text-gray-600 leading-relaxed",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "CompanyStats",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      justifyContent: "space-between",
                      flexWrap: "wrap",
                      gap: "20px",
                      marginTop: "20px",
                    },
                    tailwindStyles: "grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8 mt-8",
                    elements: [
                      {
                        type: "Frame",
                        name: "Stat1",
                        id: uuidv4(),
                        content: "",
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          textAlign: "center",
                        },
                        tailwindStyles: "flex flex-col items-center text-center",
                        elements: [
                          {
                            type: "Text",
                            content: "10,000+",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "28px",
                              fontWeight: "bold",
                              color: "#0ea5e9",
                            },
                            tailwindStyles: "text-2xl md:text-3xl font-bold text-sky-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                          {
                            type: "Text",
                            content: "Websites Built",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "14px",
                              color: "#6b7280",
                            },
                            tailwindStyles: "text-sm text-gray-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                        ],
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Frame",
                        name: "Stat2",
                        id: uuidv4(),
                        content: "",
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          textAlign: "center",
                        },
                        tailwindStyles: "flex flex-col items-center text-center",
                        elements: [
                          {
                            type: "Text",
                            content: "5,000+",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "28px",
                              fontWeight: "bold",
                              color: "#0ea5e9",
                            },
                            tailwindStyles: "text-2xl md:text-3xl font-bold text-sky-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                          {
                            type: "Text",
                            content: "Happy Customers",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "14px",
                              color: "#6b7280",
                            },
                            tailwindStyles: "text-sm text-gray-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                        ],
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Frame",
                        name: "Stat3",
                        id: uuidv4(),
                        content: "",
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          textAlign: "center",
                        },
                        tailwindStyles: "flex flex-col items-center text-center",
                        elements: [
                          {
                            type: "Text",
                            content: "15",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "28px",
                              fontWeight: "bold",
                              color: "#0ea5e9",
                            },
                            tailwindStyles: "text-2xl md:text-3xl font-bold text-sky-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                          {
                            type: "Text",
                            content: "Team Members",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "14px",
                              color: "#6b7280",
                            },
                            tailwindStyles: "text-sm text-gray-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                        ],
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Frame",
                        name: "Stat4",
                        id: uuidv4(),
                        content: "",
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          textAlign: "center",
                        },
                        tailwindStyles: "flex flex-col items-center text-center",
                        elements: [
                          {
                            type: "Text",
                            content: "24/7",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "28px",
                              fontWeight: "bold",
                              color: "#0ea5e9",
                            },
                            tailwindStyles: "text-2xl md:text-3xl font-bold text-sky-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                          {
                            type: "Text",
                            content: "Customer Support",
                            id: uuidv4(),
                            isSelected: false,
                            x: 0,
                            y: 0,
                            styles: {
                              fontSize: "14px",
                              color: "#6b7280",
                            },
                            tailwindStyles: "text-sm text-gray-500",
                            href: "",
                            src: "",
                            parentId: "",
                            projectId: "",
                          },
                        ],
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      
      {
        type: "Frame",
        name: "CTASection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          backgroundColor: "#0ea5e9",
          padding: "80px 20px",
          color: "white",
        },
        tailwindStyles: "w-full bg-sky-500 py-20 px-4 md:px-8 text-white",
        elements: [
          {
            type: "Frame",
            name: "CTAContainer",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              maxWidth: "1000px",
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
              gap: "24px",
            },
            tailwindStyles: "max-w-4xl mx-auto flex flex-col items-center text-center gap-6",
            elements: [
              {
                type: "Text",
                content: "Ready to Build Your Website?",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "36px",
                  fontWeight: "bold",
                  color: "white",
                },
                tailwindStyles: "text-3xl md:text-4xl font-bold",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Start your free trial today and see how easy it is to create a professional website with our platform.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "18px",
                  maxWidth: "700px",
                  marginTop: "10px",
                },
                tailwindStyles: "text-lg md:text-xl max-w-2xl mt-2 text-sky-50",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Button",
                content: "Start Free Trial",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                buttonType: "button",
                styles: {
                  backgroundColor: "white",
                  color: "#0ea5e9",
                  fontWeight: "600",
                  padding: "14px 28px",
                  borderRadius: "8px",
                  fontSize: "16px",
                  marginTop: "20px",
                  border: "none",
                  cursor: "pointer",
                },
                tailwindStyles: "bg-white text-sky-500 font-semibold px-7 py-3.5 rounded-lg hover:bg-sky-50 transition-colors text-lg mt-6",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "No credit card required. Free for 14 days.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  marginTop: "10px",
                  opacity: "0.9",
                },
                tailwindStyles: "text-sm mt-3 text-sky-100",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      
      {
        type: "Frame",
        name: "FooterSection",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          backgroundColor: "white",
          color: "#333333",
          padding: "60px 20px 30px",
        },
        tailwindStyles: "w-full bg-white text-gray-800 py-14 px-4 md:px-8 mt-auto shadow-md",
        elements: [
          {
            type: "Frame",
            name: "FooterContainer",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              maxWidth: "1200px",
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              gap: "40px",
            },
            tailwindStyles: "max-w-6xl mx-auto flex flex-col gap-10",
            elements: [
              {
                type: "Frame",
                name: "FooterMain",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  justifyContent: "space-between",
                  flexWrap: "wrap",
                  gap: "30px",
                },
                tailwindStyles: "grid grid-cols-1 md:grid-cols-4 gap-8",
                elements: [
                  {
                    type: "Frame",
                    name: "CompanyInfo",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "16px",
                    },
                    tailwindStyles: "flex flex-col gap-4",
                    elements: [
                      {
                        type: "Image",
                        content: "Logo",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "100px",
                          height: "40px",
                          objectFit: "contain",
                          backgroundColor: "transparent",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                        },
                        tailwindStyles: "w-24 h-10 object-contain flex items-center justify-center",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Create beautiful websites easily with our drag-and-drop website builder.",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                          lineHeight: "1.6",
                        },
                        tailwindStyles: "text-sm text-gray-400 leading-relaxed",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FooterLinks1",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "PRODUCT",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          fontWeight: "600",
                          color: "#333333",
                          marginBottom: "8px",
                        },
                        tailwindStyles: "text-sm font-semibold text-gray-800 mb-2",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Features",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Pricing",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Templates",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FooterLinks2",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "COMPANY",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          fontWeight: "600",
                          color: "#333333",
                          marginBottom: "8px",
                        },
                        tailwindStyles: "text-sm font-semibold text-gray-800 mb-2",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "About Us",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Careers",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Blog",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FooterLinks3",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "SUPPORT",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          fontWeight: "600",
                          color: "#333333",
                          marginBottom: "8px",
                        },
                        tailwindStyles: "text-sm font-semibold text-gray-800 mb-2",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Help Center",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Contact Us",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Privacy Policy",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "FooterBottom",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  borderTop: "1px solid #e5e7eb",
                  paddingTop: "20px",
                  flexWrap: "wrap",
                  gap: "20px",
                },
                tailwindStyles: "flex flex-col md:flex-row justify-between items-center border-t border-gray-200 pt-6 gap-4",
                elements: [
                  {
                    type: "Text",
                    content: "© 2025 WebBuilder. All rights reserved.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#9ca3af",
                    },
                    tailwindStyles: "text-sm text-gray-400",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "SocialLinks",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      gap: "16px",
                    },
                    tailwindStyles: "flex gap-4",
                    elements: [
                      {
                        type: "Link",
                        content: "Twitter",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Facebook",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "Instagram",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#9ca3af",
                        },
                        tailwindStyles: "text-sm text-gray-400 hover:text-sky-500 transition-colors",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const landingPageComponents = {
  landingPageTemplateComponent,
};

export default landingPageComponents;