import { FrameElement } from "@/lib/interface";
import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

// Helper function to create customizable badges
const createBadge = (
  text: string,
  bgColor: string,
  textColor: string,
  style: "rounded" | "pill" | "square" = "rounded"
) => {
  const borderRadius = {
    rounded: "8px",
    pill: "30px",
    square: "0px",
  };

  return {
    type: "Text",
    content: text,
    id: uuidv4(),
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "inline-block",
      backgroundColor: bgColor,
      padding: "4px 12px",
      borderRadius: borderRadius[style],
      fontSize: "14px",
      color: textColor,
      fontWeight: "500",
      marginBottom: "8px",
    },
    tailwindStyles: `inline-block ${
      style === "pill"
        ? "rounded-full"
        : style === "rounded"
        ? "rounded-lg"
        : ""
    } px-3 py-1 text-sm font-medium mb-2`,
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  };
};

// Function to create flexible mission content layout
const createMissionLayout = (layout: "left" | "right" | "center") => {
  const baseComponent = {
    type: "Frame",
    name: `MissionComponent_${layout}`,
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      padding: "40px 20px",
    },
    tailwindStyles: "w-full py-10 px-5",
    elements: [],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  };

  // Different layout configurations
  if (layout === "left" || layout === "right") {
    baseComponent.styles = {
      ...baseComponent.styles,
    };
    baseComponent.tailwindStyles =
      "grid grid-cols-1 md:grid-cols-2 gap-16 items-center py-10 px-5";
  } else if (layout === "center") {
    baseComponent.styles = {
      ...baseComponent.styles,
    };
    baseComponent.tailwindStyles =
      "flex flex-col items-center text-center max-w-4xl mx-auto py-10 px-5";
  }

  return baseComponent;
};

export const missionComponent1: CustomComponent = {
  component: createMissionLayout("right"),
};

// Update the component elements based on layout
(missionComponent1.component as FrameElement).elements = [
  {
    type: "Frame",
    name: "TextContent",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "flex",
      flexDirection: "column",
      gap: "24px",
      order: "2",
    },
    tailwindStyles: "space-y-6 order-2 md:order-1",
    elements: [
      createBadge("Sứ mệnh của chúng tôi", "#dbeafe", "#1e40af", "rounded"),
      {
        type: "Text",
        content: "Biến ý tưởng thành hiện thực",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "36px",
          fontWeight: "bold",
          color: "#111827",
        },
        tailwindStyles: "text-4xl font-bold text-gray-900",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content:
          "Chúng tôi ra đời với mục tiêu giúp mọi người dễ dàng tiếp cận và xây dựng giao diện web chuyên nghiệp, mà không cần kiến thức lập trình phức tạp.",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#6b7280",
          lineHeight: "1.6",
        },
        tailwindStyles: "text-lg text-muted-foreground",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "FeaturesList",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
        },
        tailwindStyles: "space-y-2",
        elements: [
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tạo ra website dễ dàng với drag & drop",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tùy chỉnh mọi phần của trang web",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tối ưu trải nghiệm người dùng",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
  {
    type: "Frame",
    name: "ImageContainer",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      borderRadius: "12px",
      overflow: "hidden",
      boxShadow:
        "0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)",
      order: "1",
    },
    tailwindStyles: "rounded-xl overflow-hidden shadow-xl order-1 md:order-2",
    elements: [
      {
        type: "Image",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          height: "auto",
          objectFit: "cover",
        },
        tailwindStyles: "w-full h-auto object-cover",
        href: "",
        src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
];

export const missionComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "MissionComponent2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      gap: "40px",
      padding: "60px 20px",
      backgroundColor: "#f9fafb",
      borderRadius: "16px",
    },
    tailwindStyles: "flex flex-col gap-10 py-16 px-5 bg-gray-50 rounded-2xl",
    elements: [
      {
        type: "Frame",
        name: "Header",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          textAlign: "center",
          marginBottom: "20px",
        },
        tailwindStyles: "text-center mb-5",
        elements: [
          createBadge("Sứ mệnh của chúng tôi", "#e0e7ff", "#4f46e5", "pill"),
          {
            type: "Text",
            content: "Biến ý tưởng thành hiện thực",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "36px",
              fontWeight: "bold",
              color: "#111827",
              maxWidth: "600px",
              margin: "0 auto",
            },
            tailwindStyles:
              "text-4xl font-bold text-gray-900 max-w-2xl mx-auto",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ContentContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "40px",
          alignItems: "center",
        },
        tailwindStyles: "grid grid-cols-1 lg:grid-cols-2 gap-10 items-center",
        elements: [
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              borderRadius: "12px",
              boxShadow:
                "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            },
            tailwindStyles: "w-full rounded-xl shadow-md",
            href: "",
            src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TextContent",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "24px",
            },
            tailwindStyles: "flex flex-col space-y-6",
            elements: [
              {
                type: "Text",
                content:
                  "Chúng tôi ra đời với mục tiêu giúp mọi người dễ dàng tiếp cận và xây dựng giao diện web chuyên nghiệp, mà không cần kiến thức lập trình phức tạp.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "18px",
                  color: "#4b5563",
                  lineHeight: "1.7",
                },
                tailwindStyles: "text-lg text-gray-600 leading-relaxed",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Features",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "16px",
                  marginTop: "16px",
                },
                tailwindStyles: "grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4",
                elements: [
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "12px",
                    },
                    tailwindStyles: "flex items-center gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "white",
                          backgroundColor: "#10b981",
                          width: "24px",
                          height: "24px",
                          borderRadius: "50%",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontWeight: "bold",
                          fontSize: "14px",
                        },
                        tailwindStyles:
                          "flex-shrink-0 h-6 w-6 rounded-full bg-green-500 text-white flex items-center justify-center text-sm font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Drag & Drop Builder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#374151",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-gray-700 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "12px",
                    },
                    tailwindStyles: "flex items-center gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "white",
                          backgroundColor: "#10b981",
                          width: "24px",
                          height: "24px",
                          borderRadius: "50%",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontWeight: "bold",
                          fontSize: "14px",
                        },
                        tailwindStyles:
                          "flex-shrink-0 h-6 w-6 rounded-full bg-green-500 text-white flex items-center justify-center text-sm font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Custom Templates",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#374151",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-gray-700 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "12px",
                    },
                    tailwindStyles: "flex items-center gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "white",
                          backgroundColor: "#10b981",
                          width: "24px",
                          height: "24px",
                          borderRadius: "50%",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontWeight: "bold",
                          fontSize: "14px",
                        },
                        tailwindStyles:
                          "flex-shrink-0 h-6 w-6 rounded-full bg-green-500 text-white flex items-center justify-center text-sm font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Responsive Design",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#374151",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-gray-700 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "12px",
                    },
                    tailwindStyles: "flex items-center gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "white",
                          backgroundColor: "#10b981",
                          width: "24px",
                          height: "24px",
                          borderRadius: "50%",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontWeight: "bold",
                          fontSize: "14px",
                        },
                        tailwindStyles:
                          "flex-shrink-0 h-6 w-6 rounded-full bg-green-500 text-white flex items-center justify-center text-sm font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Clean Code Export",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          color: "#374151",
                          fontWeight: "500",
                        },
                        tailwindStyles: "text-gray-700 font-medium",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const missionComponentLeft: CustomComponent = {
  component: createMissionLayout("left"),
};

(missionComponentLeft.component as FrameElement).elements = [
  {
    type: "Frame",
    name: "ImageContainer",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      borderRadius: "12px",
      overflow: "hidden",
      boxShadow:
        "0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)",
      order: "1",
    },
    tailwindStyles: "rounded-xl overflow-hidden shadow-xl order-1",
    elements: [
      {
        type: "Image",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          height: "auto",
          objectFit: "cover",
        },
        tailwindStyles: "w-full h-auto object-cover",
        href: "",
        src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
  {
    type: "Frame",
    name: "TextContent",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "flex",
      flexDirection: "column",
      gap: "24px",
      order: "2",
    },
    tailwindStyles: "space-y-6 order-2",
    elements: [
      createBadge("Sứ mệnh của chúng tôi", "#fef3c7", "#92400e", "square"),
      {
        type: "Text",
        content: "Biến ý tưởng thành hiện thực",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "36px",
          fontWeight: "bold",
          color: "#111827",
        },
        tailwindStyles: "text-4xl font-bold text-gray-900",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content:
          "Chúng tôi ra đời với mục tiêu giúp mọi người dễ dàng tiếp cận và xây dựng giao diện web chuyên nghiệp, mà không cần kiến thức lập trình phức tạp.",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#6b7280",
          lineHeight: "1.6",
        },
        tailwindStyles: "text-lg text-muted-foreground",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "FeaturesList",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
        },
        tailwindStyles: "space-y-2",
        elements: [
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tạo ra website dễ dàng với drag & drop",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tùy chỉnh mọi phần của trang web",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "FeatureItem",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex items-start",
            elements: [
              {
                type: "Text",
                content: "✓",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "20px",
                  color: "#22c55e",
                  marginRight: "8px",
                },
                tailwindStyles: "h-5 w-5 text-green-500 mr-2 shrink-0 mt-0.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Tối ưu trải nghiệm người dùng",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#374151",
                },
                tailwindStyles: "text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
];

export const missionComponentCentered: CustomComponent = {
  component: createMissionLayout("center"),
};
(missionComponentCentered.component as FrameElement).elements = [
  {
    type: "Frame",
    name: "HeaderContent",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "16px",
      marginBottom: "40px",
      textAlign: "center",
    },
    tailwindStyles: "flex flex-col items-center gap-4 mb-10 text-center",
    elements: [
      createBadge("Sứ mệnh", "#d1fae5", "#047857", "pill"),
      {
        type: "Text",
        content: "Biến ý tưởng thành hiện thực",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "40px",
          fontWeight: "bold",
          color: "#111827",
        },
        tailwindStyles: "text-4xl md:text-5xl font-bold text-gray-900",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content:
          "Chúng tôi ra đời với mục tiêu giúp mọi người dễ dàng tiếp cận và xây dựng giao diện web chuyên nghiệp, mà không cần kiến thức lập trình phức tạp.",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#6b7280",
          lineHeight: "1.6",
          maxWidth: "600px",
        },
        tailwindStyles: "text-lg text-gray-600 max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
  {
    type: "Image",
    content: "",
    id: uuidv4(),
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "700px",
      borderRadius: "12px",
      boxShadow:
        "0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)",
    },
    tailwindStyles: "w-full max-w-3xl rounded-xl shadow-xl",
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
];

export const missionComponentCompact: CustomComponent = {
  component: {
    type: "Frame",
    name: "MissionComponentCompact",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "900px",
      margin: "0 auto",
      padding: "30px 20px",
      borderRadius: "12px",
      backgroundColor: "#f8f9fa",
      boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyles:
      "w-full max-w-3xl mx-auto p-6 sm:p-8 rounded-xl bg-gray-50 shadow-md",
    elements: [
      {
        type: "Frame",
        name: "Header",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          alignItems: "center",
          marginBottom: "20px",
        },
        tailwindStyles: "flex items-center mb-5",
        elements: [
          {
            type: "Frame",
            name: "Badge",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              backgroundColor: "#dbeafe",
              color: "#1e40af",
              padding: "4px 10px",
              borderRadius: "6px",
              fontSize: "12px",
              fontWeight: "600",
              marginRight: "15px",
            },
            tailwindStyles:
              "bg-blue-100 text-blue-800 px-2.5 py-1 rounded-md text-xs font-semibold mr-4",
            elements: [
              {
                type: "Text",
                content: "Sứ mệnh",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {},
                tailwindStyles: "",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Biến ý tưởng thành hiện thực",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontWeight: "bold",
              fontSize: "24px",
              color: "#111827",
            },
            tailwindStyles: "font-bold text-2xl text-gray-900",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "Content",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          gap: "20px",
          alignItems: "center",
        },
        tailwindStyles: "flex flex-col md:flex-row gap-5 items-center",
        elements: [
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "180px",
              height: "180px",
              objectFit: "cover",
              borderRadius: "8px",
              flexShrink: "0",
            },
            tailwindStyles: "w-44 h-44 object-cover rounded-lg flex-shrink-0",
            href: "",
            src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TextContent",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "15px",
            },
            tailwindStyles: "flex flex-col gap-4",
            elements: [
              {
                type: "Text",
                content:
                  "Chúng tôi giúp bạn xây dựng giao diện web chuyên nghiệp mà không cần kiến thức lập trình phức tạp.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#4b5563",
                  lineHeight: "1.6",
                },
                tailwindStyles: "text-base text-gray-600 leading-relaxed",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Features",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "10px",
                },
                tailwindStyles: "grid grid-cols-1 sm:grid-cols-2 gap-2.5",
                elements: [
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Drag & Drop Builder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Responsive Design",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Custom Templates",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureItem",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Clean Code Export",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const missionComponentSlider: CustomComponent = {
  component: {
    type: "Frame",
    name: "MissionComponentSlider",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      overflow: "hidden",
      padding: "20px 0",
    },
    tailwindStyles: "w-full overflow-hidden py-5",
    elements: [
      {
        type: "Frame",
        name: "SliderContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          gap: "10px",
          width: "100%",
          overflowX: "auto",
          padding: "10px 20px",
          scrollbarWidth: "none",
        },
        tailwindStyles:
          "flex gap-3 w-full overflow-x-auto scrollbar-hide px-5 pb-2",
        elements: [
          {
            type: "Frame",
            name: "MissionCard",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              minWidth: "300px",
              backgroundColor: "white",
              borderRadius: "10px",
              padding: "20px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.12)",
              border: "1px solid #f3f4f6",
            },
            tailwindStyles:
              "flex flex-col min-w-[300px] bg-white rounded-lg p-5 shadow-sm border border-gray-100",
            elements: [
              {
                type: "Text",
                content: "Sứ mệnh",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#2563eb",
                  fontWeight: "600",
                  fontSize: "14px",
                  marginBottom: "10px",
                },
                tailwindStyles: "text-blue-600 font-semibold text-sm mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Biến ý tưởng thành hiện thực",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "18px",
                  color: "#111827",
                  marginBottom: "10px",
                },
                tailwindStyles: "font-bold text-lg text-gray-900 mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content:
                  "Giúp bạn xây dựng giao diện web chuyên nghiệp, dễ dàng mà không cần kiến thức lập trình phức tạp.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  color: "#4b5563",
                  marginBottom: "15px",
                },
                tailwindStyles: "text-sm text-gray-600 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  marginBottom: "8px",
                },
                tailwindStyles: "flex items-center gap-2 mb-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#10b981",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-green-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Drag & Drop Builder",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                },
                tailwindStyles: "flex items-center gap-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#10b981",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-green-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Clean Code Export",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "MissionCard",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              minWidth: "300px",
              backgroundColor: "#f3f4f6",
              borderRadius: "10px",
              padding: "20px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.12)",
              border: "1px solid #e5e7eb",
            },
            tailwindStyles:
              "flex flex-col min-w-[300px] bg-gray-100 rounded-lg p-5 shadow-sm border border-gray-200",
            elements: [
              {
                type: "Text",
                content: "Tầm nhìn",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#7c3aed",
                  fontWeight: "600",
                  fontSize: "14px",
                  marginBottom: "10px",
                },
                tailwindStyles: "text-purple-600 font-semibold text-sm mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Nâng cao trải nghiệm",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "18px",
                  color: "#111827",
                  marginBottom: "10px",
                },
                tailwindStyles: "font-bold text-lg text-gray-900 mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content:
                  "Trở thành công cụ xây dựng web tốt nhất, giúp người dùng tạo ra giao diện đẹp mắt.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  color: "#4b5563",
                  marginBottom: "15px",
                },
                tailwindStyles: "text-sm text-gray-600 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  marginBottom: "8px",
                },
                tailwindStyles: "flex items-center gap-2 mb-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#8b5cf6",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-purple-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "AI-powered Templates",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                },
                tailwindStyles: "flex items-center gap-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#8b5cf6",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-purple-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Advanced Analytics",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "MissionCard",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              minWidth: "300px",
              backgroundColor: "#eff6ff",
              borderRadius: "10px",
              padding: "20px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.12)",
              border: "1px solid #dbeafe",
            },
            tailwindStyles:
              "flex flex-col min-w-[300px] bg-blue-50 rounded-lg p-5 shadow-sm border border-blue-100",
            elements: [
              {
                type: "Text",
                content: "Giá trị",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#0ea5e9",
                  fontWeight: "600",
                  fontSize: "14px",
                  marginBottom: "10px",
                },
                tailwindStyles: "text-sky-500 font-semibold text-sm mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Đơn giản & Hiệu quả",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "18px",
                  color: "#111827",
                  marginBottom: "10px",
                },
                tailwindStyles: "font-bold text-lg text-gray-900 mb-2.5",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content:
                  "Chúng tôi tin rằng công cụ tốt nhất là công cụ đơn giản nhưng mạnh mẽ và hiệu quả.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  color: "#4b5563",
                  marginBottom: "15px",
                },
                tailwindStyles: "text-sm text-gray-600 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  marginBottom: "8px",
                },
                tailwindStyles: "flex items-center gap-2 mb-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#0ea5e9",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-sky-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Intuitive Interface",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Feature",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                },
                tailwindStyles: "flex items-center gap-2",
                elements: [
                  {
                    type: "Text",
                    content: "✓",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#0ea5e9",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "text-sky-500 font-bold",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Fast Performance",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const missionComponentAlternating: CustomComponent = {
  component: {
    type: "Frame",
    name: "MissionComponentAlternating",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      gap: "80px",
      padding: "60px 20px",
    },
    tailwindStyles: "w-full flex flex-col gap-20 py-16 px-5",
    elements: [
      {
        type: "Frame",
        name: "Section1",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "40px",
          alignItems: "center",
        },
        tailwindStyles: "grid grid-cols-1 md:grid-cols-2 gap-10 items-center",
        elements: [
          {
            type: "Frame",
            name: "TextContent",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "20px",
            },
            tailwindStyles: "flex flex-col gap-5",
            elements: [
              createBadge("Sứ mệnh", "#fee2e2", "#b91c1c", "rounded"),
              {
                type: "Text",
                content: "Biến ý tưởng thành hiện thực",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "32px",
                  fontWeight: "bold",
                  color: "#111827",
                },
                tailwindStyles: "text-3xl font-bold text-gray-900",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content:
                  "Chúng tôi ra đời với mục tiêu giúp mọi người dễ dàng tiếp cận và xây dựng giao diện web chuyên nghiệp.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#6b7280",
                  lineHeight: "1.6",
                },
                tailwindStyles: "text-base text-gray-600 leading-relaxed",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              borderRadius: "12px",
              boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
            },
            tailwindStyles: "w-full rounded-xl shadow-lg",
            href: "",
            src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "Section2",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "40px",
          alignItems: "center",
        },
        tailwindStyles: "grid grid-cols-1 md:grid-cols-2 gap-10 items-center",
        elements: [
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              borderRadius: "12px",
              boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
              order: "2",
            },
            tailwindStyles: "w-full rounded-xl shadow-lg order-1 md:order-2",
            href: "",
            src: "https://images.unsplash.com/photo-1598520106830-8c45c2035460?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TextContent",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "20px",
              order: "1",
            },
            tailwindStyles: "flex flex-col gap-5 order-2 md:order-1",
            elements: [
              createBadge("Tầm nhìn", "#e0e7ff", "#4f46e5", "rounded"),
              {
                type: "Text",
                content: "Nâng cao trải nghiệm",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "32px",
                  fontWeight: "bold",
                  color: "#111827",
                },
                tailwindStyles: "text-3xl font-bold text-gray-900",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content:
                  "Trở thành công cụ xây dựng web tốt nhất, giúp người dùng tạo ra giao diện đẹp mắt một cách dễ dàng.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#6b7280",
                  lineHeight: "1.6",
                },
                tailwindStyles: "text-base text-gray-600 leading-relaxed",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};