import { v4 as uuidv4 } from 'uuid';
import { CustomComponent } from "../styleconstants";

export const isOnboardingCompleted = (): boolean => {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('onboardingCompleted') === 'true';
  }
  return false;
};

export const markOnboardingCompleted = (): void => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('onboardingCompleted', 'true');
  }
};

export const onboardingComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "OnboardingFlow",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      height: "100vh",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#f9fafb",
      position: "fixed",
      top: 0,
      left: 0,
      zIndex: 1000,
    },
    tailwindStyles: "w-full h-screen flex flex-col items-center justify-center bg-gray-50 fixed inset-0 z-50",
    elements: [
      {
        type: "Frame",
        name: "OnboardingContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "90%",
          maxWidth: "800px",
          backgroundColor: "white",
          borderRadius: "12px",
          boxShadow: "0 10px 25px rgba(0,0,0,0.1)",
          padding: "30px",
          display: "flex",
          flexDirection: "column",
          gap: "24px",
          position: "relative",
        },
        tailwindStyles: "w-11/12 max-w-4xl bg-white rounded-xl shadow-lg p-6 md:p-8 flex flex-col gap-6 relative",
        elements: [
          {
            type: "Frame",
            name: "ProgressIndicator",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              display: "flex",
              justifyContent: "center",
              gap: "6px",
              marginBottom: "20px",
            },
            tailwindStyles: "w-full flex justify-center gap-1.5 mb-5",
            elements: [
              {
                type: "Frame",
                name: "Step1",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "40px",
                  height: "6px",
                  borderRadius: "3px",
                  backgroundColor: "#3b82f6",
                },
                tailwindStyles: "w-10 h-1.5 rounded-full bg-blue-500",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Step2",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "40px",
                  height: "6px",
                  borderRadius: "3px",
                  backgroundColor: "#e5e7eb",
                },
                tailwindStyles: "w-10 h-1.5 rounded-full bg-gray-200",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Step3",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "40px",
                  height: "6px",
                  borderRadius: "3px",
                  backgroundColor: "#e5e7eb",
                },
                tailwindStyles: "w-10 h-1.5 rounded-full bg-gray-200",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "Step4",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "40px",
                  height: "6px",
                  borderRadius: "3px",
                  backgroundColor: "#e5e7eb",
                },
                tailwindStyles: "w-10 h-1.5 rounded-full bg-gray-200",
                elements: [],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Step1-Carousel",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            },
            tailwindStyles: "flex flex-col items-center text-center",
            elements: [
              {
                type: "Text",
                content: "Chào mừng đến với WebBuilder",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "28px",
                  fontWeight: "bold",
                  color: "#111827",
                  marginBottom: "16px",
                },
                tailwindStyles: "text-2xl md:text-3xl font-bold text-gray-900 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "CarouselContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "300px",
                  borderRadius: "8px",
                  overflow: "hidden",
                  position: "relative",
                  marginBottom: "24px",
                  backgroundColor: "#f3f4f6",
                },
                tailwindStyles: "w-full h-64 md:h-80 rounded-lg overflow-hidden relative mb-6 bg-gray-100",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                    },
                    tailwindStyles: "w-full h-full object-cover",
                    href: "",
                    src: "https://via.placeholder.com/800x400/3b82f6/ffffff?text=Welcome+to+WebBuilder",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Bắt đầu hành trình xây dựng website chuyên nghiệp với công cụ drag & drop trực quan của chúng tôi.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#4b5563",
                  maxWidth: "600px",
                  lineHeight: "1.6",
                  marginBottom: "24px",
                },
                tailwindStyles: "text-base text-gray-600 max-w-xl leading-relaxed mb-6",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Step2-About",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "none",
              flexDirection: "column",
              alignItems: "center",
            },
            tailwindStyles: "hidden flex-col items-center",
            elements: [
              {
                type: "Text",
                content: "Về chúng tôi",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "28px",
                  fontWeight: "bold",
                  color: "#111827",
                  marginBottom: "16px",
                },
                tailwindStyles: "text-2xl md:text-3xl font-bold text-gray-900 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "AboutContent",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "column",
                  gap: "16px",
                  width: "100%",
                },
                tailwindStyles: "flex flex-col gap-4 w-full",
                elements: [
                  {
                    type: "Text",
                    content: "WebBuilder được phát triển với sứ mệnh giúp mọi người xây dựng website chuyên nghiệp mà không cần kiến thức lập trình phức tạp.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "16px",
                      color: "#4b5563",
                      lineHeight: "1.6",
                    },
                    tailwindStyles: "text-base text-gray-600 leading-relaxed",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "Feature",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                      marginTop: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2 mt-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Drag & Drop Builder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      }
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "Feature",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Tùy chỉnh không giới hạn",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      }
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "Feature",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                    },
                    tailwindStyles: "flex items-center gap-2",
                    elements: [
                      {
                        type: "Text",
                        content: "✓",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          color: "#10b981",
                          fontWeight: "bold",
                        },
                        tailwindStyles: "text-green-500 font-bold",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Export mã code chất lượng cao",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      }
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Step3-Features",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "none",
              flexDirection: "column",
              alignItems: "center",
            },
            tailwindStyles: "hidden flex-col items-center",
            elements: [
              {
                type: "Text",
                content: "Tính năng nổi bật",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "28px",
                  fontWeight: "bold",
                  color: "#111827",
                  marginBottom: "16px",
                },
                tailwindStyles: "text-2xl md:text-3xl font-bold text-gray-900 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "FeaturesGrid",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "20px",
                  width: "100%",
                },
                tailwindStyles: "grid grid-cols-1 sm:grid-cols-2 gap-5 w-full",
                elements: [
                  {
                    type: "Frame",
                    name: "FeatureCard",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "20px",
                      borderRadius: "8px",
                      backgroundColor: "#f3f4f6",
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "p-5 rounded-lg bg-gray-100 flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "Drag & Drop Builder",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-base font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Dễ dàng kéo thả các phần tử để tạo giao diện web đẹp mắt",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#4b5563",
                        },
                        tailwindStyles: "text-sm text-gray-600",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureCard",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "20px",
                      borderRadius: "8px",
                      backgroundColor: "#f3f4f6",
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "p-5 rounded-lg bg-gray-100 flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "Thư viện mẫu phong phú",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-base font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Hàng trăm mẫu thiết kế đẹp mắt sẵn sàng sử dụng",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#4b5563",
                        },
                        tailwindStyles: "text-sm text-gray-600",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureCard",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "20px",
                      borderRadius: "8px",
                      backgroundColor: "#f3f4f6",
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "p-5 rounded-lg bg-gray-100 flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "Tương thích di động 100%",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-base font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Website tạo ra hoạt động mượt mà trên mọi thiết bị",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#4b5563",
                        },
                        tailwindStyles: "text-sm text-gray-600",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "FeatureCard",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "20px",
                      borderRadius: "8px",
                      backgroundColor: "#f3f4f6",
                      display: "flex",
                      flexDirection: "column",
                      gap: "12px",
                    },
                    tailwindStyles: "p-5 rounded-lg bg-gray-100 flex flex-col gap-3",
                    elements: [
                      {
                        type: "Text",
                        content: "Tùy chỉnh nâng cao",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "16px",
                          fontWeight: "600",
                          color: "#111827",
                        },
                        tailwindStyles: "text-base font-semibold text-gray-900",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Text",
                        content: "Kiểm soát hoàn toàn phong cách và bố cục của trang web",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          color: "#4b5563",
                        },
                        tailwindStyles: "text-sm text-gray-600",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Step4-GetStarted",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "none",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            },
            tailwindStyles: "hidden flex-col items-center text-center",
            elements: [
              {
                type: "Text",
                content: "Bắt đầu ngay!",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "28px",
                  fontWeight: "bold",
                  color: "#111827",
                  marginBottom: "16px",
                },
                tailwindStyles: "text-2xl md:text-3xl font-bold text-gray-900 mb-4",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Image",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "200px",
                  height: "200px",
                  objectFit: "contain",
                  marginBottom: "20px",
                },
                tailwindStyles: "w-32 h-32 md:w-48 md:h-48 object-contain mb-5",
                href: "",
                src: "https://via.placeholder.com/200/3b82f6/ffffff?text=Success",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Chúc mừng bạn đã hoàn thành quá trình giới thiệu! Bây giờ bạn đã sẵn sàng để bắt đầu xây dựng website đầu tiên của mình.",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#4b5563",
                  maxWidth: "600px",
                  lineHeight: "1.6",
                  marginBottom: "24px",
                },
                tailwindStyles: "text-base text-gray-600 max-w-xl leading-relaxed mb-6",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "NavigationButtons",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              display: "flex",
              justifyContent: "space-between",
              marginTop: "20px",
            },
            tailwindStyles: "w-full flex justify-between items-center mt-5",
            elements: [
              {
                type: "Link",
                content: "Bỏ qua",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#6b7280",
                  fontSize: "14px",
                  padding: "8px 16px",
                  borderRadius: "4px",
                  cursor: "pointer",
                  transition: "all 0.2s ease",
                },
                tailwindStyles: "text-gray-500 text-sm py-2 px-4 rounded cursor-pointer hover:text-gray-700 transition-colors",
                href: "#skip-onboarding",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "RightButtons",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  gap: "12px",
                },
                tailwindStyles: "flex gap-3",
                elements: [
                  {
                    type: "Link",
                    content: "Quay lại",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "none",
                      color: "#6b7280",
                      fontSize: "14px",
                      padding: "8px 16px",
                      borderRadius: "4px",
                      cursor: "pointer",
                      transition: "all 0.2s ease",
                    },
                    tailwindStyles: "hidden text-gray-500 text-sm py-2 px-4 rounded cursor-pointer hover:text-gray-700 transition-colors",
                    href: "#prev-step",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Tiếp theo",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      backgroundColor: "#3b82f6",
                      color: "white",
                      fontSize: "14px",
                      padding: "8px 20px",
                      borderRadius: "4px",
                      fontWeight: "500",
                      cursor: "pointer",
                      transition: "all 0.2s ease",
                    },
                    tailwindStyles: "bg-blue-500 text-white text-sm py-2 px-5 rounded font-medium cursor-pointer hover:bg-blue-600 transition-colors",
                    href: "#next-step",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Hoàn thành",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "none",
                      backgroundColor: "#10b981",
                      color: "white",
                      fontSize: "14px",
                      padding: "8px 20px",
                      borderRadius: "4px",
                      fontWeight: "500",
                      cursor: "pointer",
                      transition: "all 0.2s ease",
                    },
                    tailwindStyles: "hidden bg-green-500 text-white text-sm py-2 px-5 rounded font-medium cursor-pointer hover:bg-green-600 transition-colors",
                    href: "#complete-onboarding",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "const onboardingScript = () => {\n  let currentStep = 1;\n  const totalSteps = 4;\n\n  // Elements\n  const steps = [\n    document.querySelector('[name=\"Step1-Carousel\"]'),\n    document.querySelector('[name=\"Step2-About\"]'),\n    document.querySelector('[name=\"Step3-Features\"]'),\n    document.querySelector('[name=\"Step4-GetStarted\"]')\n  ];\n  \n  const indicators = [\n    document.querySelector('[name=\"Step1\"]'),\n    document.querySelector('[name=\"Step2\"]'),\n    document.querySelector('[name=\"Step3\"]'),\n    document.querySelector('[name=\"Step4\"]')\n  ];\n\n  const nextBtn = document.querySelector('[content=\"Tiếp theo\"]');\n  const prevBtn = document.querySelector('[content=\"Quay lại\"]');\n  const completeBtn = document.querySelector('[content=\"Hoàn thành\"]');\n  const skipBtn = document.querySelector('[content=\"Bỏ qua\"]');\n\n  // Functions\n  function showStep(stepNumber) {\n    steps.forEach((step, index) => {\n      if (index === stepNumber - 1) {\n        step.style.display = 'flex';\n      } else {\n        step.style.display = 'none';\n      }\n    });\n\n    indicators.forEach((indicator, index) => {\n      if (index < stepNumber) {\n        indicator.style.backgroundColor = '#3b82f6';\n      } else {\n        indicator.style.backgroundColor = '#e5e7eb';\n      }\n    });\n\n    prevBtn.style.display = stepNumber > 1 ? 'block' : 'none';\n    \n    if (stepNumber === totalSteps) {\n      nextBtn.style.display = 'none';\n      completeBtn.style.display = 'block';\n    } else {\n      nextBtn.style.display = 'block';\n      completeBtn.style.display = 'none';\n    }\n  }\n\n  function nextStep() {\n    if (currentStep < totalSteps) {\n      currentStep++;\n      showStep(currentStep);\n    }\n  }\n\n  function prevStep() {\n    if (currentStep > 1) {\n      currentStep--;\n      showStep(currentStep);\n    }\n  }\n\n  function completeOnboarding() {\n    localStorage.setItem('onboardingCompleted', 'true');\n    document.querySelector('[name=\"OnboardingFlow\"]').style.display = 'none';\n  }\n\n  // Event listeners\n  nextBtn && nextBtn.addEventListener('click', (e) => {\n    e.preventDefault();\n    nextStep();\n  });\n\n  prevBtn && prevBtn.addEventListener('click', (e) => {\n    e.preventDefault();\n    prevStep();\n  });\n\n  completeBtn && completeBtn.addEventListener('click', (e) => {\n    e.preventDefault();\n    completeOnboarding();\n  });\n\n  skipBtn && skipBtn.addEventListener('click', (e) => {\n    e.preventDefault();\n    completeOnboarding();\n  });\n\n  // Check if onboarding was already completed\n  if (localStorage.getItem('onboardingCompleted') === 'true') {\n    document.querySelector('[name=\"OnboardingFlow\"]').style.display = 'none';\n  }\n};\n\n// Execute the script when available\nif (typeof window !== 'undefined') {\n  window.addEventListener('load', onboardingScript);\n}",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "none",
              position: "absolute",
              visibility: "hidden",
            },
            tailwindStyles: "hidden absolute invisible",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      }
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  }
};