import { CanvasStyles } from "../store/canvasStore";

export const Presets: { name: string; styles: CanvasStyles }[] = [
  {
    name: "Default",
    styles: {
      backgroundColor: "#ffffff",
      width: "100%",
      height: "100%",
      gridEnabled: false,
      gridSize: 8,
      snapToGrid: false,
      overflow: "auto",
      gridColor: "#dddddd",
    },
  },
  {
    name: "Dark Mode",
    styles: {
      backgroundColor: "#121212",
      width: "100%",
      height: "100%",
      gridEnabled: true,
      gridSize: 10,
      snapToGrid: true,
      gridColor: "#333333",
      overflow: "auto",
      transition: "all 0.2s ease",
    },
  },
  {
    name: "Minimal",
    styles: {
      backgroundColor: "#f8f8f8",
      width: "100%",
      height: "100%",
      maxWidth: "1200px",
      gridEnabled: false,
      overflow: "auto",
      borderRadius: "8px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
      transition: "all 0.3s ease",
    },
  },
  {
    name: "Professional",
    styles: {
      backgroundColor: "#ffffff",
      width: "100%",
      height: "100%",
      maxWidth: "1024px",
      gridEnabled: true,
      gridSize: 12,
      snapToGrid: true,
      gridColor: "#e0e0e0",
      overflow: "auto",
      borderRadius: "4px",
      border: "1px solid #e0e0e0",
      boxShadow: "0 2px 4px rgba(0,0,0,0.08)",
    },
  },
  {
    name: "Creative",
    styles: {
      backgroundColor: "#fffaf0",
      width: "100%",
      height: "100%",
      gridEnabled: true,
      gridSize: 16,
      snapToGrid: false,
      gridColor: "#f0e6d2",
      overflow: "auto",
      borderRadius: "12px",
      boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
      transition: "all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
    },
  },
  {
    name: "Glassmorphism",
    styles: {
      backgroundColor: "rgba(255, 255, 255, 0.15)",
      width: "100%",
      height: "100%",
      gridEnabled: false,
      overflow: "auto",
      borderRadius: "16px",
      border: "1px solid rgba(255, 255, 255, 0.18)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
      backdropFilter: "blur(8px)",
      transition: "all 0.3s ease",
    },
  },
  {
    name: "Mobile-Focused",
    styles: {
      backgroundColor: "#ffffff",
      width: "375px",
      height: "667px",
      gridEnabled: true,
      gridSize: 4,
      snapToGrid: true,
      gridColor: "#f0f0f0",
      overflow: "auto",
      borderRadius: "20px",
      boxShadow: "0 12px 24px rgba(0,0,0,0.12)",
      transition: "all 0.2s ease",
    },
  },
  {
    name: "Tablet",
    styles: {
      backgroundColor: "#ffffff",
      width: "768px",
      height: "1024px",
      gridEnabled: true,
      gridSize: 8,
      snapToGrid: true,
      gridColor: "#e8e8e8",
      overflow: "auto",
      borderRadius: "12px",
      boxShadow: "0 10px 20px rgba(0,0,0,0.08)",
      transition: "all 0.25s ease",
    },
  },
  {
    name: "Blueprint",
    styles: {
      backgroundColor: "#1a237e",
      width: "100%",
      height: "100%",
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      gridColor: "#3949ab",
      overflow: "auto",
      transition: "all 0.2s ease",
    },
  },
  {
    name: "Modern",
    styles: {
      backgroundColor: "#fafafa",
      width: "100%",
      height: "100%",
      maxWidth: "1400px",
      gridEnabled: false,
      overflow: "auto",
      borderRadius: "10px",
      boxShadow: "0 6px 16px rgba(0,0,0,0.06)",
      transition: "all 0.25s ease",
    },
  },
];

export default Presets;