import { EditorElement } from "./type";
import { v4 as uuidv4 } from "uuid";
export interface CustomComponent {
  component: EditorElement;
}

const navbarComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "50px",
      width: "100%",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
    },
    tailwindStyles: "flex flex-row items-center w-full",
    elements: [
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "black",
          margin: "0 10px",
        },
        tailwindStyles: "m-0",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "About",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "black",
          margin: "0 10px",
        },
        tailwindStyles: "m-0",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "60px",
      width: "100%",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 20px",
    },
    tailwindStyles: "flex flex-row items-center justify-between w-full p-5 bg-gray-900",
    elements: [
      {
        type: "Text",
        content: "LOGO",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontWeight: "bold",
          fontSize: "24px",
        },
        tailwindStyles: "text-white font-bold text-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "Links",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyles: "flex flex-row items-center",
        elements: [
          {
            type: "Link",
            content: "Home",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyles: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Services",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyles: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Contact",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyles: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "65px",
      width: "100%",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
    },
    tailwindStyles: "flex flex-row items-center justify-center w-full bg-gray-100 shadow",
    elements: [
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyles: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Products",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyles: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Gallery",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyles: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          backgroundColor: "#007bff",
          transition: "all 0.3s ease",
        },
        tailwindStyles: "mx-5 text-white font-medium px-4 py-2 rounded bg-blue-500 hover:bg-blue-600",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "transparent",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 30px",
      borderBottom: "1px solid #e0e0e0",
    },
    tailwindStyles: "flex flex-row items-center justify-between w-full px-8 border-b border-gray-200",
    elements: [
      {
        type: "Text",
        content: "BRAND",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontWeight: "bold",
          fontSize: "22px",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-gray-800 font-bold text-xl tracking-wide",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NavMenu",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyles: "flex flex-row items-center",
        elements: [
          {
            type: "Link",
            content: "Home",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyles: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "About",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyles: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Services",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyles: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent5: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar5",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "55px",
      width: "100%",
      backgroundColor: "#6200ea",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      padding: "0 15px",
      color: "white",
    },
    tailwindStyles: "flex flex-row items-center justify-start w-full p-4 bg-purple-800 text-white",
    elements: [
      {
        type: "Text",
        content: "App Name",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontWeight: "bold",
          fontSize: "20px",
          marginRight: "30px",
        },
        tailwindStyles: "text-white font-bold text-xl mr-8",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyles: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Projects",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyles: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Tasks",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyles: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyles: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "80px",
      width: "100%",
      backgroundColor: "#333",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      padding: "20px 0",
    },
    tailwindStyles:
      "flex flex-row items-center justify-around w-full p-5 bg-gray-800",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyles: "text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Privacy Policy",
        id: "3",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Terms of Service",
        id: "4",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "100px",
      width: "100%",
      backgroundColor: "#2c3e50",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyles:
      "flex flex-col items-center justify-center w-full p-5 bg-blue-900",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginBottom: "10px",
        },
        tailwindStyles: "text-white mb-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact Us",
        id: "6",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/contact",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "90px",
      width: "100%",
      backgroundColor: "#8e44ad",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyles:
      "flex flex-row items-center justify-center w-full p-5 bg-purple-700",
    elements: [
      {
        type: "Text",
        content: "Follow Us",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginRight: "10px",
        },
        tailwindStyles: "text-white mr-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Facebook",
        id: "5",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          display: "flex",
          alignItems: "center",
        },
        tailwindStyles: "m-2 flex items-center text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "70px",
      width: "100%",
      backgroundColor: "#4a4a4a",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "20px 40px",
    },
    tailwindStyles:
      "flex flex-row items-center justify-between w-full p-5 bg-gray-700",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyles: "text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "About Us",
        id: "7",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/about",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Services",
        id: "8",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact",
        id: "9",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "#e3f2fd",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyles:
      "flex flex-row items-center justify-between w-full p-4 bg-blue-100 shadow-md",
    elements: [
      {
        type: "Text",
        content: "My Portfolio",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyles: "text-blue-900 text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "1",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-blue-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Projects",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-blue-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "#343a40",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyles:
      "flex flex-row items-center justify-center w-full p-4 bg-gray-900 shadow-md",
    elements: [
      {
        type: "Text",
        content: "Brothers Inc",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyles: "text-white text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-white text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Portfolio",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-white text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "80px",
      width: "100%",
      backgroundColor: "#4caf50",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyles:
      "flex flex-row items-center justify-start w-full p-4 bg-green-500 shadow-md",
    elements: [
      {
        type: "Text",
        content: "Welcome to My Site",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyles: "text-green-900 text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-green-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Pricing",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyles: "m-2 text-green-900 text-lg",
        href: "/articles",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarLeftComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "250px",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 10px",
      boxShadow: "2px 0 5px rgba(0,0,0,0.1)",
    },
    tailwindStyles: "flex flex-col items-start w-64 h-screen p-4 bg-white shadow-md",
    elements: [
      {
        type: "Text",
        content: "Dashboard",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "20px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Analytics",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Reports",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "8px 10px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-2 px-3 hover:bg-gray-100 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarLeftComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "280px",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 15px",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-screen p-6 bg-gray-900",
    elements: [
      {
        type: "Text",
        content: "ADMIN PANEL",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "30px",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-white text-lg font-bold mb-8 tracking-wide",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
          backgroundColor: "#393e46",
        },
        tailwindStyles: "w-full text-white my-3 py-2 px-4 bg-gray-800 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Users",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#d1d1d1",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
        },
        tailwindStyles: "w-full text-gray-300 my-3 py-2 px-4 hover:bg-gray-800 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#d1d1d1",
          margin: "12px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 15px",
          borderRadius: "5px",
        },
        tailwindStyles: "w-full text-gray-300 my-3 py-2 px-4 hover:bg-gray-800 rounded",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarLeftComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "240px",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 12px",
      borderRight: "1px solid #e0e0e0",
    },
    tailwindStyles: "flex flex-col items-start w-60 h-screen p-5 bg-gray-100 border-r border-gray-200",
    elements: [
      {
        type: "Text",
        content: "Menu",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#6c757d",
          fontSize: "14px",
          fontWeight: "500",
          marginBottom: "15px",
          textTransform: "uppercase",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-gray-500 text-sm font-medium mb-4 uppercase tracking-wide",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Products",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Orders",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#495057",
          margin: "8px 0",
          fontSize: "16px",
          width: "100%",
          padding: "10px 12px",
          borderRadius: "6px",
          transition: "all 0.2s ease",
        },
        tailwindStyles: "w-full text-gray-700 my-2 py-2 px-3 rounded hover:bg-blue-50 hover:text-blue-600",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarLeftComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarLeft4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "260px",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "30px 15px",
      borderRight: "1px solid #eaeaea",
    },
    tailwindStyles: "flex flex-col items-center w-64 h-screen p-7 bg-white border-r border-gray-100",
    elements: [
      {
        type: "Text",
        content: "BRAND",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "22px",
          fontWeight: "bold",
          marginBottom: "40px",
          letterSpacing: "2px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-10 tracking-wider",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Profile",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#555",
          margin: "10px 0",
          fontSize: "16px",
          width: "100%",
          padding: "12px 15px",
          textAlign: "center",
          borderRadius: "8px",
        },
        tailwindStyles: "w-full text-gray-600 my-2 py-3 px-4 text-center rounded-lg hover:bg-gray-50",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarRightComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "300px",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 15px",
      boxShadow: "-2px 0 5px rgba(0,0,0,0.1)",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-screen p-5 bg-white shadow-md fixed right-0 top-0",
    elements: [
      {
        type: "Text",
        content: "Notifications",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "20px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-xl font-bold mb-5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NotificationItem",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "12px",
          borderBottom: "1px solid #eee",
          display: "flex",
          flexDirection: "column",
        },
        tailwindStyles: "w-full p-3 border-b border-gray-100 flex flex-col",
        elements: [
          {
            type: "Text",
            content: "New message received",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-gray-800 text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "5 minutes ago",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#888",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-500 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarRightComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "320px",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 15px",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-80 h-screen p-6 bg-gray-900 fixed right-0 top-0",
    elements: [
      {
        type: "Text",
        content: "ACTIVITY FEED",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "30px",
          letterSpacing: "1px",
        },
        tailwindStyles: "text-white text-lg font-bold mb-8 tracking-wide",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ActivityItem",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "15px",
          backgroundColor: "#393e46",
          borderRadius: "8px",
          marginBottom: "15px",
          display: "flex",
          flexDirection: "column",
        },
        tailwindStyles: "w-full p-4 bg-gray-800 rounded-lg mb-4 flex flex-col",
        elements: [
          {
            type: "Text",
            content: "",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-white text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "5 minutes ago",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#aaa",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-400 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarRightComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "280px",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "20px 15px",
      borderLeft: "1px solid #e0e0e0",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-72 h-screen p-5 bg-gray-100 border-l border-gray-200 fixed right-0 top-0",
    elements: [
      {
        type: "Text",
        content: "Recent Updates",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#343a40",
          fontSize: "18px",
          fontWeight: "600",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-lg font-semibold mb-5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "UpdateItem",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "12px",
          backgroundColor: "white",
          borderRadius: "6px",
          marginBottom: "12px",
          display: "flex",
          flexDirection: "column",
          boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
        },
        tailwindStyles: "w-full p-3 bg-white rounded-md mb-3 flex flex-col shadow-sm",
        elements: [
          {
            type: "Text",
            content: "Product Update v2.1",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
              fontWeight: "500",
            },
            tailwindStyles: "text-gray-800 text-md font-medium",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#6c757d",
              fontSize: "14px",
              marginTop: "5px",
            },
            tailwindStyles: "text-gray-600 text-sm mt-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const sidebarRightComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "SidebarRight4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "100vh",
      width: "330px",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      padding: "25px 20px",
      boxShadow: "-2px 0 10px rgba(0,0,0,0.05)",
      position: "fixed",
      right: "0",
      top: "0",
    },
    tailwindStyles: "flex flex-col items-start w-80 h-screen p-6 bg-white shadow-md fixed right-0 top-0",
    elements: [
      {
        type: "Text",
        content: "People Online",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontSize: "18px",
          fontWeight: "bold",
          marginBottom: "20px",
        },
        tailwindStyles: "text-gray-800 text-lg font-bold mb-5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "UserItem",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          padding: "10px 0",
          borderBottom: "1px solid #f0f0f0",
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyles: "w-full py-2 border-b border-gray-100 flex flex-row items-center",
        elements: [
          {
            type: "Text",
            content: "•",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#4CAF50",
              fontSize: "24px",
              marginRight: "10px",
            },
            tailwindStyles: "text-green-500 text-2xl mr-2",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              fontSize: "16px",
            },
            tailwindStyles: "text-gray-800 text-md",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const customComponents: CustomComponent[] = [
  navbarComponent,
  navbarComponent2,
  navbarComponent3,
  navbarComponent4,
  navbarComponent5,
  footerComponent,
  footerComponent2,
  footerComponent3,
  footerComponent4,
  headerComponent,
  headerComponent2,
  headerComponent3,
  sidebarLeftComponent,
  sidebarLeftComponent2,
  sidebarLeftComponent3,
  sidebarLeftComponent4,
  sidebarRightComponent,
  sidebarRightComponent2,
  sidebarRightComponent3,
  sidebarRightComponent4,
];
