import { EditorElement } from "./type";
import { v4 as uuidv4 } from "uuid";
export interface CustomComponent {
  component: EditorElement;
}

const navbarComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "50px",
      width: "100%",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
    },
    tailwindStyle: "flex flex-row items-center w-full",
    elements: [
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "black",
          margin: "0 10px",
        },
        tailwindStyle: "m-0",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "About",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "black",
          margin: "0 10px",
        },
        tailwindStyle: "m-0",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar2",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "60px",
      width: "100%",
      backgroundColor: "#222831",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 20px",
    },
    tailwindStyle: "flex flex-row items-center justify-between w-full p-5 bg-gray-900",
    elements: [
      {
        type: "Text",
        content: "LOGO",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontWeight: "bold",
          fontSize: "24px",
        },
        tailwindStyle: "text-white font-bold text-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "Links",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyle: "flex flex-row items-center",
        elements: [
          {
            type: "Link",
            content: "Home",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyle: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Services",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyle: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Contact",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "white",
              margin: "0 15px",
              fontSize: "16px",
            },
            tailwindStyle: "m-4 text-white",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar3",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "65px",
      width: "100%",
      backgroundColor: "#f8f9fa",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
    },
    tailwindStyle: "flex flex-row items-center justify-center w-full bg-gray-100 shadow",
    elements: [
      {
        type: "Link",
        content: "Home",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyle: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Products",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyle: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Gallery",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          transition: "all 0.3s ease",
        },
        tailwindStyle: "mx-5 text-gray-800 font-medium px-4 py-2 rounded hover:bg-blue-100",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
          fontWeight: "500",
          fontSize: "17px",
          padding: "8px 15px",
          borderRadius: "4px",
          backgroundColor: "#007bff",
          transition: "all 0.3s ease",
        },
        tailwindStyle: "mx-5 text-white font-medium px-4 py-2 rounded bg-blue-500 hover:bg-blue-600",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar4",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "transparent",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 30px",
      borderBottom: "1px solid #e0e0e0",
    },
    tailwindStyle: "flex flex-row items-center justify-between w-full px-8 border-b border-gray-200",
    elements: [
      {
        type: "Text",
        content: "BRAND",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#333",
          fontWeight: "bold",
          fontSize: "22px",
          letterSpacing: "1px",
        },
        tailwindStyle: "text-gray-800 font-bold text-xl tracking-wide",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NavMenu",
        id: "",
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
        },
        tailwindStyle: "flex flex-row items-center",
        elements: [
          {
            type: "Link",
            content: "Home",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyle: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "About",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyle: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Services",
            id: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              color: "#333",
              margin: "0 20px",
              fontSize: "16px",
              position: "relative",
              textDecoration: "none",
            },
            tailwindStyle: "mx-5 text-gray-800 relative no-underline",
            href: "/",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const navbarComponent5: CustomComponent = {
  component: {
    type: "Frame",
    name: "NavBar5",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "55px",
      width: "100%",
      backgroundColor: "#6200ea",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      padding: "0 15px",
      color: "white",
    },
    tailwindStyle: "flex flex-row items-center justify-start w-full p-4 bg-purple-800 text-white",
    elements: [
      {
        type: "Text",
        content: "App Name",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontWeight: "bold",
          fontSize: "20px",
          marginRight: "30px",
        },
        tailwindStyle: "text-white font-bold text-xl mr-8",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Dashboard",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyle: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Projects",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyle: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Tasks",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyle: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Settings",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 15px",
          fontSize: "16px",
        },
        tailwindStyle: "mx-4 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "80px",
      width: "100%",
      backgroundColor: "#333",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      padding: "20px 0",
    },
    tailwindStyle:
      "flex flex-row items-center justify-around w-full p-5 bg-gray-800",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyle: "text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Privacy Policy",
        id: "3",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Terms of Service",
        id: "4",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer2",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "100px",
      width: "100%",
      backgroundColor: "#2c3e50",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyle:
      "flex flex-col items-center justify-center w-full p-5 bg-blue-900",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginBottom: "10px",
        },
        tailwindStyle: "text-white mb-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact Us",
        id: "6",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/contact",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer3",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "90px",
      width: "100%",
      backgroundColor: "#8e44ad",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyle:
      "flex flex-row items-center justify-center w-full p-5 bg-purple-700",
    elements: [
      {
        type: "Text",
        content: "Follow Us",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginRight: "10px",
        },
        tailwindStyle: "text-white mr-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Facebook",
        id: "5",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          display: "flex",
          alignItems: "center",
        },
        tailwindStyle: "m-2 flex items-center text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const footerComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer4",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "70px",
      width: "100%",
      backgroundColor: "#4a4a4a",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "20px 40px",
    },
    tailwindStyle:
      "flex flex-row items-center justify-between w-full p-5 bg-gray-700",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyle: "text-white",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "About Us",
        id: "7",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/about",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Services",
        id: "8",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact",
        id: "9",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyle: "m-2 text-white",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "#e3f2fd",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyle:
      "flex flex-row items-center justify-between w-full p-4 bg-blue-100 shadow-md",
    elements: [
      {
        type: "Text",
        content: "My Portfolio",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyle: "text-blue-900 text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "1",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-blue-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Projects",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#0d47a1",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-blue-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header2",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "70px",
      width: "100%",
      backgroundColor: "#343a40",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyle:
      "flex flex-row items-center justify-center w-full p-4 bg-gray-900 shadow-md",
    elements: [
      {
        type: "Text",
        content: "Brothers Inc",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyle: "text-white text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "1",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-white text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Portfolio",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-white text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

const headerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Header3",
    id: "",
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      height: "80px",
      width: "100%",
      backgroundColor: "#4caf50",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      padding: "0 20px",
      boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    },
    tailwindStyle:
      "flex flex-row items-center justify-start w-full p-4 bg-green-500 shadow-md",
    elements: [
      {
        type: "Text",
        content: "Welcome to My Site",
        id: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          fontSize: "28px",
          fontWeight: "bold",
        },
        tailwindStyle: "text-green-900 text-3xl font-bold",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Home",
        id: "1",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-green-900 text-lg",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Pricing",
        id: "2",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "#1b5e20",
          margin: "0 10px",
          fontSize: "18px",
        },
        tailwindStyle: "m-2 text-green-900 text-lg",
        href: "/articles",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const customComponents: CustomComponent[] = [
  navbarComponent,
  navbarComponent2,
  navbarComponent3,
  navbarComponent4,
  navbarComponent5,
  footerComponent,
  footerComponent2,
  footerComponent3,
  footerComponent4,
  headerComponent,
  headerComponent2,
  headerComponent3,
];
