import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

// Contact Form
export const formComponent1: CustomComponent = {
  component: {
    type: "Form",
    name: "Form1",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      margin: "0 auto",
      padding: "20px", 
      borderRadius: "12px",
      boxShadow: "0 4px 14px rgba(0, 0, 0, 0.07)",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    tailwindStyles: "w-full mx-auto rounded-xl shadow-lg bg-white flex flex-col overflow-hidden p-4 md:p-6",
    elements: [
      {
        type: "Frame",
        name: "FormHeader",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          marginBottom: "16px",
        },
        tailwindStyles: "w-full mb-3 md:mb-5",
        elements: [
          {
            type: "Text",
            content: "Thông tin liên hệ",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "24px", 
              fontWeight: "700",
              color: "#111827",
              padding: "12px 0", 
              width: "100%",
              textAlign: "center",
            },
            tailwindStyles: "text-xl md:text-2xl font-bold text-gray-900 py-2 md:py-3 text-center w-full",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ContentContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          width: "100%",
          padding: "0px 24px 24px",
          gap: "24px",
        },
        tailwindStyles: "w-full flex flex-col md:flex-row px-2 md:px-5 gap-5 md:gap-6",
        elements: [
          {
            type: "Image",
            name: "ContactImage",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "40%",
              objectFit: "cover",
              borderRadius: "8px",
              height: "100%",
            },
            tailwindStyles: "w-full md:w-2/5 h-56 md:h-auto object-cover rounded-lg mb-5 md:mb-0",
            href: "",
            src: "https://images.unsplash.com/photo-1557804506-669a67965ba0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "FormContainer",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "16px",
              width: "60%",
            },
            tailwindStyles: "w-full md:w-3/5 flex flex-col gap-4 md:gap-5",
            elements: [
              {
                type: "Frame",
                name: "NameInputGroup",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "column",
                  gap: "8px",
                  width: "100%",
                },
                tailwindStyles: "flex flex-col gap-2 w-full mb-3 md:mb-0",
                elements: [
                  {
                    type: "Text",
                    content: "Họ và tên",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      fontWeight: "500",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm font-medium text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Input",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "10px 14px",
                      border: "1px solid #e5e7eb",
                      borderRadius: "6px",
                      width: "100%",
                      fontSize: "14px",
                    },
                    tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                    inputSettings: {
                      type: "text",
                      placeholder: "",
                      required: true,
                      name: "name",
                    },
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "ContactInfoGroup",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "16px",
                  width: "100%",
                },
                tailwindStyles: "flex flex-col sm:flex-row gap-4 w-full",
                elements: [
                  {
                    type: "Frame",
                    name: "EmailInputGroup",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "8px",
                      width: "50%",
                    },
                    tailwindStyles: "flex flex-col gap-2 w-full sm:w-1/2 mb-3 sm:mb-0 sm:mr-2",
                    elements: [
                      {
                        type: "Text",
                        content: "Email",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          fontWeight: "500",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm font-medium text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Input",
                        content: "",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "10px 14px",
                          border: "1px solid #e5e7eb",
                          borderRadius: "6px",
                          width: "100%",
                          fontSize: "14px",
                        },
                        tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                        inputSettings: {
                          type: "email",
                          placeholder: "",
                          required: true,
                          name: "email",
                        },
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "PhoneInputGroup",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "column",
                      gap: "8px",
                      width: "50%",
                    },
                    tailwindStyles: "flex flex-col gap-2 w-full sm:w-1/2 sm:ml-2",
                    elements: [
                      {
                        type: "Text",
                        content: "Số điện thoại",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          fontSize: "14px",
                          fontWeight: "500",
                          color: "#374151",
                        },
                        tailwindStyles: "text-sm font-medium text-gray-700",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Input",
                        content: "",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "10px 14px",
                          border: "1px solid #e5e7eb",
                          borderRadius: "6px",
                          width: "100%",
                          fontSize: "14px",
                        },
                        tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                        inputSettings: {
                          type: "tel",
                          placeholder: "",
                          required: false,
                          name: "phone",
                        },
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "MessageInputGroup",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "column",
                  gap: "8px",
                  width: "100%",
                },
                tailwindStyles: "flex flex-col gap-2 w-full mt-3 md:mt-0",
                elements: [
                  {
                    type: "Text",
                    content: "Nội dung liên hệ",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      fontWeight: "500",
                      color: "#374151",
                    },
                    tailwindStyles: "text-sm font-medium text-gray-700",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      padding: "10px 14px",
                      border: "1px solid #e5e7eb",
                      borderRadius: "6px",
                      width: "100%",
                      fontSize: "14px",
                      minHeight: "140px",
                    },
                    tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500 min-h-[140px]",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                    elements: [
                      {
                        type: "Input",
                        content: "",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          width: "100%",
                          height: "100%",
                          border: "none",
                          outline: "none",
                          resize: "none",
                        },
                        tailwindStyles: "w-full h-full border-none outline-none resize-none bg-transparent",
                        href: "",
                        src: "",
                        parentId: "",
                        projectId: "",
                        inputSettings: {
                          type: "textarea",
                          placeholder: "",
                          required: true,
                          name: "message",
                        },
                      },
                    ],
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Button",
        content: "Submit",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        buttonType: "submit",
        styles: {
          backgroundColor: "#3b82f6",
          color: "#ffffff",
          padding: "12px 20px",
          fontWeight: "500",
          fontSize: "14px",
          cursor: "pointer",
          border: "none",
          width: "100%",
          borderRadius: "6px",
        },
        tailwindStyles: "bg-blue-500 hover:bg-blue-600 text-white py-3 px-5 font-medium text-sm cursor-pointer border-none w-full rounded-md transition-colors mt-4 md:mt-6",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
    formSettings: {
      method: "post",
      autocomplete: "on",
      noValidate: false,
    },
  },
};

// Login Form
export const formComponent2: CustomComponent = {
  component: {
    type: "Form",
    name: "Form2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      margin: "0 auto",
      padding: "24px 30px",
      borderRadius: "12px",
      boxShadow: "0 4px 14px rgba(0, 0, 0, 0.07)",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      gap: "18px",
      alignItems: "center", 
    },
    tailwindStyles: "w-full mx-auto p-5 sm:p-6 md:p-8 rounded-xl shadow-lg bg-white flex flex-col gap-3 sm:gap-4 md:gap-5 items-center",
    elements: [
      {
        type: "Text",
        content: "Sign In",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "24px",
          fontWeight: "700",
          color: "#111827",
          marginBottom: "8px",
          textAlign: "center",
        },
        tailwindStyles: "text-xl sm:text-2xl font-bold text-gray-900 mb-1 sm:mb-2 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Enter your credentials to access your account",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "14px",
          color: "#6b7280",
          marginBottom: "16px",
          textAlign: "center",
        },
        tailwindStyles: "text-xs sm:text-sm text-gray-500 mb-3 sm:mb-4 text-center px-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "FormFields",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          maxWidth: "350px", 
          display: "flex",
          flexDirection: "column",
          gap: "16px",
          margin: "0 auto", 
        },
        tailwindStyles: "w-full max-w-[350px] flex flex-col gap-3 sm:gap-4 mx-auto",
        elements: [
          {
            type: "Frame",
            name: "EmailInputGroup",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              width: "100%",
            },
            tailwindStyles: "flex flex-col gap-2 w-full",
            elements: [
              {
                type: "Text",
                content: "Email",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  fontWeight: "500",
                  color: "#374151",
                },
                tailwindStyles: "text-sm font-medium text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Input",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  padding: "10px 14px",
                  border: "1px solid #e5e7eb",
                  borderRadius: "6px",
                  width: "100%",
                  fontSize: "14px",
                },
                tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
                inputSettings: {
                  type: "email",
                  placeholder: "Your email address",
                  required: true,
                  name: "email",
                },
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "PasswordInputGroup",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              gap: "8px",
              width: "100%",
              marginTop: "8px",
            },
            tailwindStyles: "flex flex-col gap-2 w-full mt-2",
            elements: [
              {
                type: "Text",
                content: "Password",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  fontWeight: "500",
                  color: "#374151",
                },
                tailwindStyles: "text-sm font-medium text-gray-700",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Input",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  padding: "10px 14px",
                  border: "1px solid #e5e7eb",
                  borderRadius: "6px",
                  width: "100%",
                  fontSize: "14px",
                },
                tailwindStyles: "w-full px-3.5 py-2.5 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
                inputSettings: {
                  type: "password",
                  placeholder: "Enter your password",
                  required: true,
                  name: "password",
                },
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Forgot your password?",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#3b82f6",
              textAlign: "right", 
              marginTop: "4px",
            },
            tailwindStyles: "text-sm text-blue-500 hover:underline text-right mt-1",
            href: "/forgot-password",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Button",
        content: "Sign In",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        buttonType: "submit",
        styles: {
          backgroundColor: "#3b82f6",
          color: "#ffffff",
          padding: "10px 16px",
          borderRadius: "6px",
          fontWeight: "500",
          fontSize: "14px",
          cursor: "pointer",
          border: "none",
          marginTop: "16px",
          width: "100%",
          maxWidth: "350px", 
          margin: "16px auto 0", 
        },
        tailwindStyles: "bg-blue-500 text-white py-2 sm:py-2.5 px-3 sm:px-4 rounded-md font-medium text-sm cursor-pointer border-none mt-3 sm:mt-4 w-full max-w-[350px] mx-auto hover:bg-blue-600 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "SignUpLink",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "center",
          marginTop: "16px",
          width: "100%",
          maxWidth: "350px", 
          margin: "16px auto 0", 
        },
        tailwindStyles: "flex justify-center mt-3 sm:mt-4 w-full max-w-[350px] mx-auto",
        elements: [
          {
            type: "Text",
            content: "Don't have an account? ",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#6b7280",
            },
            tailwindStyles: "text-xs sm:text-sm text-gray-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Sign Up",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#3b82f6",
              marginLeft: "4px",
            },
            tailwindStyles: "text-xs sm:text-sm text-blue-500 ml-1 hover:underline",
            href: "/register",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
    formSettings: {
      method: "post",
      autocomplete: "on",
      noValidate: false,
    },
  },
};