import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

// Contact Form
export const formComponent1: CustomComponent = {
  component: {
    type: "Form",
    name: "Form1",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "500px",
      margin: "0 auto",
      padding: "24px",
      borderRadius: "8px",
      boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    tailwindStyles: "w-full max-w-lg mx-auto p-6 rounded-lg shadow-md bg-white flex flex-col gap-4",
    elements: [
      {
        type: "Text",
        content: "Contact Us",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "24px",
          fontWeight: "700",
          color: "#111827",
          marginBottom: "8px",
        },
        tailwindStyles: "text-2xl font-bold text-gray-900 mb-2",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Fill out the form below and we'll get back to you as soon as possible.",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "14px",
          color: "#6b7280",
          marginBottom: "16px",
        },
        tailwindStyles: "text-sm text-gray-500 mb-4",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NameInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Name",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Input",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            inputSettings: {
              type: "text",
              placeholder: "Your full name",
              required: true,
              name: "name",
            },
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "EmailInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Email",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Input",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            inputSettings: {
              type: "email",
              placeholder: "Your email address",
              required: true,
              name: "email",
            },
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "SubjectInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Subject",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Input",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            inputSettings: {
              type: "text",
              placeholder: "What is this regarding?",
              required: true,
              name: "subject",
            },
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "MessageInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Message",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
              minHeight: "120px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500 min-h-[120px]",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Input",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "100%",
                  height: "100%",
                  border: "none",
                  outline: "none",
                  resize: "none",
                },
                tailwindStyles: "w-full h-full border-none outline-hidden resize-none bg-transparent",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
                inputSettings: {
                  type: "textarea",
                  placeholder: "Your message",
                  required: true,
                  name: "message",
                },
              },
            ],
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Button",
        content: "Send Message",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        buttonType: "submit",
        styles: {
          backgroundColor: "#3b82f6",
          color: "#ffffff",
          padding: "10px 16px",
          borderRadius: "6px",
          fontWeight: "500",
          fontSize: "14px",
          cursor: "pointer",
          border: "none",
          marginTop: "8px",
          width: "100%",
        },
        tailwindStyles: "bg-blue-500 text-white py-2.5 px-4 rounded-md font-medium text-sm cursor-pointer border-none mt-2 w-full hover:bg-blue-600 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
    formSettings: {
      method: "post",
      autocomplete: "on",
      noValidate: false,
    },
  },
};

// Login Form
export const formComponent2: CustomComponent = {
  component: {
    type: "Form",
    name: "Form2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      maxWidth: "400px",
      margin: "0 auto",
      padding: "24px",
      borderRadius: "8px",
      boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    tailwindStyles: "w-full max-w-md mx-auto p-6 rounded-lg shadow-md bg-white flex flex-col gap-4",
    elements: [
      {
        type: "Text",
        content: "Sign In",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "24px",
          fontWeight: "700",
          color: "#111827",
          marginBottom: "8px",
          textAlign: "center",
        },
        tailwindStyles: "text-2xl font-bold text-gray-900 mb-2 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Enter your credentials to access your account",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "14px",
          color: "#6b7280",
          marginBottom: "16px",
          textAlign: "center",
        },
        tailwindStyles: "text-sm text-gray-500 mb-4 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "EmailInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Email",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Input",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            inputSettings: {
              type: "email",
              placeholder: "Your email address",
              required: true,
              name: "email",
            },
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "PasswordInputGroup",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          width: "100%",
        },
        tailwindStyles: "flex flex-col gap-2 w-full",
        elements: [
          {
            type: "Text",
            content: "Password",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              fontWeight: "500",
              color: "#374151",
            },
            tailwindStyles: "text-sm font-medium text-gray-700",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Input",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "8px 12px",
              border: "1px solid #e5e7eb",
              borderRadius: "6px",
              width: "100%",
              fontSize: "14px",
            },
            tailwindStyles: "w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
            inputSettings: {
              type: "password",
              placeholder: "Your password",
              required: true,
              name: "password",
            },
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "RememberMe",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginTop: "8px",
        },
        tailwindStyles: "flex justify-between items-center mt-2",
        elements: [
          {
            type: "Frame",
            name: "RememberMeCheckbox",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              alignItems: "center",
              gap: "8px",
            },
            tailwindStyles: "flex items-center gap-2",
            elements: [
              {
                type: "Input",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "16px",
                  height: "16px",
                },
                tailwindStyles: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
                inputSettings: {
                  type: "checkbox",
                  name: "remember",
                },
              },
              {
                type: "Text",
                content: "Remember me",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "14px",
                  color: "#6b7280",
                },
                tailwindStyles: "text-sm text-gray-500",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Forgot password?",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#3b82f6",
            },
            tailwindStyles: "text-sm text-blue-500 hover:underline",
            href: "/forgot-password",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Button",
        content: "Sign In",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        buttonType: "submit",
        styles: {
          backgroundColor: "#3b82f6",
          color: "#ffffff",
          padding: "10px 16px",
          borderRadius: "6px",
          fontWeight: "500",
          fontSize: "14px",
          cursor: "pointer",
          border: "none",
          marginTop: "16px",
          width: "100%",
        },
        tailwindStyles: "bg-blue-500 text-white py-2.5 px-4 rounded-md font-medium text-sm cursor-pointer border-none mt-4 w-full hover:bg-blue-600 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "SignUpLink",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "center",
          marginTop: "16px",
        },
        tailwindStyles: "flex justify-center mt-4",
        elements: [
          {
            type: "Text",
            content: "Don't have an account? ",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#6b7280",
            },
            tailwindStyles: "text-sm text-gray-500",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Sign Up",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#3b82f6",
              marginLeft: "4px",
            },
            tailwindStyles: "text-sm text-blue-500 ml-1 hover:underline",
            href: "/register",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
    formSettings: {
      method: "post",
      autocomplete: "on",
      noValidate: false,
    },
  },
};