import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const footerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "80px",
      width: "100%",
      backgroundColor: "#333",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      padding: "20px 0",
    },
    tailwindStyles:
      "absolute bottom-0 h-[80px] w-full bg-gray-800 flex flex-col md:flex-row items-center justify-center md:justify-around py-5 px-4",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyles: "text-white text-center md:text-left hover:text-gray-300 hover:border-2 hover:border-gray-500 hover:rounded-lg transition-all",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Privacy Policy",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyles: "m-2 text-white text-center md:text-left hover:text-gray-300 hover:border-2 hover:border-gray-500 hover:rounded-lg transition-all",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Terms of Service",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 20px",
        },
        tailwindStyles: "m-2 text-white text-center md:text-left hover:text-gray-300 hover:border-2 hover:border-gray-500 hover:rounded-lg transition-all",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const footerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "100px",
      width: "100%",
      backgroundColor: "#2c3e50",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyles:
      "flex flex-col items-center justify-center w-full p-5 bg-blue-900 gap-2 md:gap-4",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginBottom: "10px",
        },
        tailwindStyles: "text-white text-center text-sm md:text-base mb-2 hover:text-blue-300 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact Us",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white text-center text-sm md:text-base hover:text-blue-300 transition-colors",
        href: "/contact",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const footerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "90px",
      width: "100%",
      backgroundColor: "#8e44ad",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyles:
      "flex flex-col md:flex-row items-center justify-center w-full p-5 bg-purple-700 gap-2 md:gap-4",
    elements: [
      {
        type: "Text",
        content: "Follow Us",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          marginRight: "10px",
        },
        tailwindStyles: "text-white text-center text-sm md:text-base mb-2 md:mb-0 hover:text-purple-300 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Facebook",
        id: "5",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
          display: "flex",
          alignItems: "center",
        },
        tailwindStyles: "m-2 flex items-center text-white text-center text-sm md:text-base hover:text-purple-300 transition-colors",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const footerComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 590,
    styles: {
      position: "absolute",
      bottom: "0",
      height: "70px",
      width: "100%",
      backgroundColor: "#4a4a4a",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "20px 40px",
    },
    tailwindStyles:
      "absolute bottom-0 h-[70px] w-full bg-gray-700 flex flex-col md:flex-row items-center justify-between px-5 md:px-10 py-3 md:py-5 gap-2 md:gap-0",
    elements: [
      {
        type: "Text",
        content: "© 2025 My Website",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
        },
        tailwindStyles: "text-white text-center md:text-left hover:text-gray-300 hover:underline transition-all",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "About Us",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white text-center md:text-left hover:text-gray-300 hover:underline transition-all",
        href: "/about",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Services",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white text-center md:text-left hover:text-gray-300 hover:underline transition-all",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Link",
        content: "Contact",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          color: "white",
          margin: "0 10px",
        },
        tailwindStyles: "m-2 text-white text-center md:text-left hover:text-gray-300 hover:underline transition-all",
        href: "/",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};