import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const footerComponent: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 450,
    styles: {
      position: "relative",
      width: "100%",
      marginTop: "auto",
      height: "auto",
      backgroundColor: "#f8f9fa",
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "20px",
      padding: "40px",
    },
    tailwindStyles:
      "w-full mt-auto bg-[#f8f9fa] grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5 py-6 px-4 sm:py-8 sm:px-6 md:py-10 md:px-8",
    elements: [
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-4",
        projectId: "",
        parentId: "",
        elements: [
          {
            type: "Image",
            content: "Logo",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: { width: "80px", height: "80px" },
            tailwindStyles: "w-20 h-20",
            projectId: "",
            parentId: "",
          },
          {
            type: "Text",
            content:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: { color: "#6c757d", fontSize: "14px" },
            tailwindStyles: "text-gray-600 text-sm",
            projectId: "",
            parentId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        projectId: "",
        parentId: "",
        elements: [
          {
            type: "Text",
            content: "Services",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: { color: "#ff6f61", fontWeight: "bold" },
            tailwindStyles: "text-[#ff6f61] font-bold",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Email Marketing",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Campaigns",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Branding",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Offline",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        projectId: "",
        parentId: "",
        elements: [
          {
            type: "Text",
            content: "About",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: { color: "#ff6f61", fontWeight: "bold" },
            tailwindStyles: "text-[#ff6f61] font-bold",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Our Story",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Benefits",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Team",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Careers",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        projectId: "",
        parentId: "",
        elements: [
          {
            type: "Text",
            content: "Follow Us",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: { color: "#ff6f61", fontWeight: "bold" },
            tailwindStyles: "text-[#ff6f61] font-bold",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Facebook",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://facebook.com",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Twitter",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://twitter.com",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
          {
            type: "Link",
            content: "Instagram",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://instagram.com",
            src: "",
            styles: { color: "#333" },
            tailwindStyles: "text-[#333] hover:underline",
            projectId: "",
            parentId: "",
          },
        ],
      },
    ],
  },
};

export const footerComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 500,
    styles: {
      position: "relative",
      width: "100%",
      marginTop: "auto",
      height: "auto",
      backgroundColor: "#f8f9fa",
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "20px",
      padding: "20px",
    },
    tailwindStyles:
      "w-full mt-auto bg-gray-100 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5 py-5 px-4 sm:px-6",
    elements: [
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "COMPANY NAME",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              color: "#000",
              fontWeight: "bold",
            },
            tailwindStyles: "text-black font-bold",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content:
              "Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 text-sm",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "PRODUCTS",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              color: "#000",
              fontWeight: "bold",
            },
            tailwindStyles: "text-black font-bold",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "MDBootstrap",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "MDWordPress",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "BrandFlow",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Bootstrap Angular",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "USEFUL LINKS",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              color: "#000",
              fontWeight: "bold",
            },
            tailwindStyles: "text-black font-bold",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Your Account",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Become an Affiliate",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Shipping Rates",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "Help",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#6c757d",
            },
            tailwindStyles: "text-gray-600 hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "CONTACT",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              color: "#000",
              fontWeight: "bold",
            },
            tailwindStyles: "text-black font-bold",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              gap: "10px",
            },
            tailwindStyles: "flex flex-row items-center gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Image",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "https://cdn-icons-png.flaticon.com/512/684/684908.png",
                styles: { 
                  width: "24px", 
                  height: "24px", 
                  objectFit: "contain" 
                },
                tailwindStyles: "w-6 h-6 object-contain" ,
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "New York, NY 10012, US",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#6c757d",
                },
                tailwindStyles: "text-gray-600",
                parentId: "",
                projectId: "",
              },
            ],
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              gap: "10px",
            },
            tailwindStyles: "flex flex-row items-center gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Image",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "https://cdn-icons-png.flaticon.com/512/732/732200.png",
                styles: { 
                  width: "24px", 
                  height: "24px", 
                  objectFit: "contain" 
                },
                tailwindStyles: "w-6 h-6 object-contain" ,
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "info@example.com",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#6c757d",
                },
                tailwindStyles: "text-gray-600",
                parentId: "",
                projectId: "",
              },
            ],
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              gap: "10px",
            },
            tailwindStyles: "flex flex-row items-center gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Image",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "https://cdn-icons-png.flaticon.com/512/724/724664.png",
                styles: { 
                  width: "24px", 
                  height: "24px", 
                  objectFit: "contain" 
                },
                tailwindStyles: "w-6 h-6 object-contain" ,
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "+ 01 234 567 88",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#6c757d",
                },
                tailwindStyles: "text-gray-600",
                parentId: "",
                projectId: "",
              },
            ],
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              gap: "10px",
            },
            tailwindStyles: "flex flex-row items-center gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Image",
                content: "",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "https://cdn-icons-png.flaticon.com/512/724/724664.png",
                styles: { 
                  width: "24px", 
                  height: "24px", 
                  objectFit: "contain" 
                },
                tailwindStyles: "w-6 h-6 object-contain" ,
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "+ 01 234 567 89",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#6c757d",
                },
                tailwindStyles: "text-gray-600",
                parentId: "",
                projectId: "",
              },
            ],
          },
        ],
      },
    ],
  },
};

export const footerComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 450,
    styles: {
      position: "relative",
      width: "100%",
      marginTop: "auto",
      height: "auto",
      backgroundColor: "#1a202c",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px 0",
    },
    tailwindStyles:
      "w-full mt-auto bg-[#1a202c] flex flex-col items-center justify-center py-5 gap-5",
    elements: [
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-around",
          width: "100%",
          maxWidth: "1200px",
        },
        tailwindStyles: "flex flex-row justify-around w-full max-w-[1200px] gap-10",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex flex-col items-start gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Text",
                content: "RESOURCES",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#ffffff",
                  fontWeight: "bold",
                },
                tailwindStyles: "text-white font-bold",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Flowbite",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "/",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Tailwind CSS",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "/",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
            ],
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex flex-col items-start gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Text",
                content: "FOLLOW US",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#ffffff",
                  fontWeight: "bold",
                },
                tailwindStyles: "text-white font-bold",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Github",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "https://github.com",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Discord",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "https://discord.com",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
            ],
          },
          {
            type: "Frame",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "",
            src: "",
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
            },
            tailwindStyles: "flex flex-col items-start gap-2",
            parentId: "",
            projectId: "",
            elements: [
              {
                type: "Text",
                content: "LEGAL",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "",
                src: "",
                styles: {
                  color: "#ffffff",
                  fontWeight: "bold",
                },
                tailwindStyles: "text-white font-bold",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Privacy Policy",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "/privacy-policy",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Terms & Conditions",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                href: "/terms",
                src: "",
                styles: {
                  color: "#a0aec0",
                },
                tailwindStyles: "text-gray-400 hover:text-white",
                parentId: "",
                projectId: "",
              },
            ],
          },
        ],
      },
      {
        type: "Text",
        content: "© 2023 Flowbite™. All Rights Reserved.",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          color: "#ffffff",
          fontSize: "14px",
          textAlign: "center",
        },
        tailwindStyles: "text-white text-sm text-center mt-5",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          gap: "15px",
        },
        tailwindStyles: "flex flex-row justify-center gap-4 mt-3",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://facebook.com",
            src: "https://cdn-icons-png.flaticon.com/512/733/733547.png",
            styles: {
              width: "24px",
              height: "24px",
            },
            tailwindStyles: "w-6 h-6",
            parentId: "",
            projectId: "",
          },
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://discord.com",
            src: "https://cdn-icons-png.flaticon.com/512/2111/2111370.png",
            styles: {
              width: "24px",
              height: "24px",
            },
            tailwindStyles: "w-6 h-6",
            parentId: "",
            projectId: "",
          },
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://twitter.com",
            src: "https://cdn-icons-png.flaticon.com/512/733/733579.png",
            styles: {
              width: "24px",
              height: "24px",
            },
            tailwindStyles: "w-6 h-6",
            parentId: "",
            projectId: "",
          },
          {
            type: "Image",
            content: "",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "https://github.com",
            src: "https://cdn-icons-png.flaticon.com/512/733/733553.png",
            styles: {
              width: "24px",
              height: "24px",
            },
            tailwindStyles: "w-6 h-6",
            parentId: "",
            projectId: "",
          },
        ],
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const footerComponent4: CustomComponent = {
  component: {
    type: "Frame",
    name: "Footer4",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 500,
    styles: {
      position: "relative",
      width: "100%",
      marginTop: "auto",
      height: "auto",
      backgroundColor: "#fbeee6",
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "20px",
      padding: "20px",
    },
    tailwindStyles:
      "w-full mt-auto bg-[#fbeee6] grid grid-cols-1 md:grid-cols-4 gap-5 py-5 px-4",
    elements: [
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "/",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start text-left gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "shopping online",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#8b4513",
              fontWeight: "bold",
              marginBottom: "10px",
            },
            tailwindStyles: "text-[#8b4513] font-bold mb-2",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "frequently asked questions",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "delivery",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "pricing",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "where we deliver?",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "/",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start text-left gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "gift cards",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#8b4513",
              fontWeight: "bold",
              marginBottom: "10px",
            },
            tailwindStyles: "text-[#8b4513] font-bold mb-2",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "frequently asked questions",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "delivery and payment",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "activate the card",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "rules",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "/",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start text-left gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "company",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#8b4513",
              fontWeight: "bold",
              marginBottom: "10px",
            },
            tailwindStyles: "text-[#8b4513] font-bold mb-2",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "buy a gift card",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "history",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "return",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "contact",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
      {
        type: "Frame",
        content: "",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        href: "/",
        src: "",
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
        },
        tailwindStyles: "flex flex-col items-start text-left gap-2",
        parentId: "",
        projectId: "",
        elements: [
          {
            type: "Text",
            content: "diamond club",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#8b4513",
              fontWeight: "bold",
              marginBottom: "10px",
            },
            tailwindStyles: "text-[#8b4513] font-bold mb-2",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "registration",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "application",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "about program",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "text-[#333] mb-1 hover:underline",
            parentId: "",
            projectId: "",
          },
          {
            type: "Link",
            content: "rules",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            href: "/",
            src: "",
            styles: {
              color: "#333",
            },
            tailwindStyles: "text-[#333] hover:underline",
            parentId: "",
            projectId: "",
          },
        ],
      },
    ],
  },
};