import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

// Helper function to create a team member card - vertical layout
const createTeamMemberVertical = (
  name: string = "Team Member",
  role: string = "Position",
  description: string = "Short description about the team member and their expertise.",
  imageSrc: string = "",
  socialLinks: Array<{ title: string; url: string; color: string }> = []
) => {
  return {
    type: "Frame",
    name: "TeamMember",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "20px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      width: "100%",
      maxWidth: "300px",
      margin: "0 auto", // Center the card within its grid cell
    },
    tailwindStyles: "flex flex-col items-center p-5 bg-white rounded-xl shadow-md w-full max-w-xs mx-auto",
    elements: [
      {
        type: "Image",
        content: "Team Member Image",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "120px",
          height: "120px",
          borderRadius: "50%",
          objectFit: "cover",
          marginBottom: "15px",
          border: imageSrc ? "none" : "2px dashed #ccc",
          display: imageSrc ? "block" : "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "#aaa",
          backgroundColor: imageSrc ? "transparent" : "#f9f9f9",
          fontSize: "14px",
          fontWeight: "bold",
        },
        tailwindStyles: "w-32 h-32 rounded-full object-cover mb-4 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
        href: "",
        src: imageSrc,
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: name,
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "20px",
          color: "#333",
          marginBottom: "5px",
        },
        tailwindStyles: "font-bold text-xl text-gray-800 mb-1",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: role,
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "16px",
          color: "#6d28d9",
          marginBottom: "15px",
        },
        tailwindStyles: "text-md text-purple-700 mb-4",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: description,
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "14px",
          color: "#666",
          textAlign: "center",
          marginBottom: "20px",
        },
        tailwindStyles: "text-sm text-gray-600 text-center mb-5",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "SocialLinks",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          gap: "15px",
        },
        tailwindStyles: "flex flex-row gap-4",
        elements: socialLinks.map(link => ({
          type: "Link",
          content: link.title,
          id: uuidv4(),
          isSelected: false,
          x: 0,
          y: 0,
          styles: {
            color: link.color,
            fontSize: "14px",
          },
          tailwindStyles: `text-${link.color} text-sm hover:underline`,
          href: link.url,
          src: "",
          parentId: "",
          projectId: "",
        })),
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  };
};

// Helper function to create a team member card - horizontal layout
const createTeamMemberHorizontal = (
  name: string = "Team Member",
  role: string = "Position",
  description: string = "Short description about the team member and their expertise.",
  imageSrc: string = "",
  socialLinks: Array<{ title: string; url: string; color: string }> = []
) => {
  return {
    type: "Frame",
    name: "TeamMemberHorizontal",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      padding: "20px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      width: "100%",
      gap: "20px",
      margin: "0 auto",
    },
    tailwindStyles: "flex flex-col sm:flex-row items-center p-5 bg-white rounded-xl shadow-md w-full gap-5 mx-auto",
    elements: [
      {
        type: "Image",
        content: "Team Member Image",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "120px",
          height: "120px",
          borderRadius: "50%",
          objectFit: "cover",
          flexShrink: "0",
          border: imageSrc ? "none" : "2px dashed #ccc",
          display: imageSrc ? "block" : "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "#aaa",
          backgroundColor: imageSrc ? "transparent" : "#f9f9f9",
          fontSize: "14px",
          fontWeight: "bold",
        },
        tailwindStyles: "w-32 h-32 rounded-full object-cover flex-shrink-0 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
        href: "",
        src: imageSrc,
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "ContentContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          flex: "1",
        },
        tailwindStyles: "flex flex-col flex-1",
        elements: [
          {
            type: "Text",
            content: name,
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontWeight: "bold",
              fontSize: "20px",
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "font-bold text-xl text-gray-800 mb-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: role,
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "16px",
              color: "#6d28d9",
              marginBottom: "10px",
            },
            tailwindStyles: "text-md text-purple-700 mb-2.5",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: description,
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#666",
              marginBottom: "15px",
            },
            tailwindStyles: "text-sm text-gray-600 mb-4",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "SocialLinks",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "row",
              gap: "15px",
            },
            tailwindStyles: "flex flex-row gap-4",
            elements: socialLinks.map(link => ({
              type: "Link",
              content: link.title,
              id: uuidv4(),
              isSelected: false,
              x: 0,
              y: 0,
              styles: {
                color: link.color,
                fontSize: "14px",
              },
              tailwindStyles: `text-${link.color} text-sm hover:underline`,
              href: link.url,
              src: "",
              parentId: "",
              projectId: "",
            })),
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  };
};

// Dynamic Team Members Grid - Vertical
export const teamMembersDynamicVertical: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembersDynamicVertical",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "40px 20px",
    },
    tailwindStyles: "w-full flex flex-col items-center p-10",
    elements: [
      {
        type: "Text",
        content: "Our Team",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "32px",
          color: "#1e293b",
          marginBottom: "20px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-3xl text-slate-800 mb-5 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Meet our talented team of professionals",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#64748b",
          marginBottom: "40px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-slate-500 mb-10 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamGrid",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
          gap: "30px",
          maxWidth: "1200px",
        },
        tailwindStyles: "w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-7 max-w-6xl",
        elements: [
          createTeamMemberVertical(
            "Jane Doe",
            "Product Designer",
            "Jane has over 10 years of experience in UX design and loves creating intuitive interfaces.",
            "",
            [
              { title: "LinkedIn", url: "https://linkedin.com", color: "blue-600" },
              { title: "Twitter", url: "https://twitter.com", color: "blue-400" }
            ]
          )
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const teamMembersDynamicHorizontal: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembersDynamicHorizontal",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "40px 20px",
      backgroundColor: "#f8fafc",
    },
    tailwindStyles: "w-full flex flex-col items-center p-10 bg-slate-50",
    elements: [
      {
        type: "Text",
        content: "Meet Our Team",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "32px",
          color: "#1e293b",
          marginBottom: "20px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-3xl text-slate-800 mb-5 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Get to know the experts behind our success",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#64748b",
          marginBottom: "40px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-slate-500 mb-10 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamList",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          display: "flex",
          flexDirection: "column",
          gap: "20px",
          maxWidth: "1000px",
        },
        tailwindStyles: "w-full flex flex-col gap-5 max-w-4xl",
        elements: [
          createTeamMemberHorizontal(
            "Jane Doe",
            "Product Designer",
            "Jane has over 10 years of experience in UX design and loves creating intuitive interfaces.",
            "",
            [
              { title: "LinkedIn", url: "https://linkedin.com", color: "blue-600" },
              { title: "Twitter", url: "https://twitter.com", color: "blue-400" }
            ]
          ),
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Carousel Team Members - Vertical
export const teamMembersCarouselVertical: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembersCarouselVertical",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "40px 20px",
      backgroundColor: "#f8fafc",
      position: "relative",
    },
    tailwindStyles: "w-full flex flex-col items-center p-10 bg-slate-50 relative",
    elements: [
      {
        type: "Text",
        content: "Our Team",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "32px",
          color: "#1e293b",
          marginBottom: "20px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-3xl text-slate-800 mb-5 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Swipe to meet our team members",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#64748b",
          marginBottom: "30px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-slate-500 mb-8 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "CarouselContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          maxWidth: "1200px",
          position: "relative",
          overflow: "hidden",
        },
        tailwindStyles: "w-full max-w-6xl relative overflow-hidden",
        elements: [
          {
            type: "Frame",
            name: "CarouselTrack",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              overflowX: "auto",
              scrollbarWidth: "none",
              padding: "10px",
              scrollSnapType: "x mandatory",
              gap: "20px",
            },
            tailwindStyles: "flex overflow-x-auto scrollbar-hide p-2.5 snap-x snap-mandatory gap-5",
            elements: [
              createTeamMemberVertical(
                "Jane Doe",
                "Product Designer",
                "Jane has over 10 years of experience in UX design and loves creating intuitive interfaces.",
                "",
                [
                  { title: "LinkedIn", url: "https://linkedin.com", color: "blue-600" },
                  { title: "Twitter", url: "https://twitter.com", color: "blue-400" }
                ]
              ),
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "NavigationControls",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "center",
          gap: "20px",
          marginTop: "30px",
        },
        tailwindStyles: "flex justify-center gap-5 mt-8",
        elements: [
          {
            type: "Frame",
            name: "PrevButton",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "10px 20px",
              backgroundColor: "#3b82f6",
              color: "white",
              borderRadius: "6px",
              cursor: "pointer",
              userSelect: "none",
            },
            tailwindStyles: "px-5 py-2.5 bg-blue-500 text-white rounded-md cursor-pointer select-none",
            elements: [
              {
                type: "Text",
                content: "Previous",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "white",
                  fontWeight: "500",
                },
                tailwindStyles: "text-white font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "NextButton",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              padding: "10px 20px",
              backgroundColor: "#3b82f6",
              color: "white",
              borderRadius: "6px",
              cursor: "pointer",
              userSelect: "none",
            },
            tailwindStyles: "px-5 py-2.5 bg-blue-500 text-white rounded-md cursor-pointer select-none",
            elements: [
              {
                type: "Text",
                content: "Next",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "white",
                  fontWeight: "500",
                },
                tailwindStyles: "text-white font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Carousel Team Members - Horizontal
export const teamMembersCarouselHorizontal: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembersCarouselHorizontal",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "50px 20px",
      backgroundColor: "#ffffff",
      position: "relative",
    },
    tailwindStyles: "w-full flex flex-col items-center py-12 px-5 bg-white relative",
    elements: [
      {
        type: "Text",
        content: "Meet The Team",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "36px",
          color: "#1e293b",
          marginBottom: "20px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-4xl text-slate-800 mb-5 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "Learn more about our talented professionals",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#64748b",
          marginBottom: "40px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-slate-500 mb-10 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "CarouselContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          maxWidth: "1200px",
          position: "relative",
        },
        tailwindStyles: "w-full max-w-6xl relative",
        elements: [
          {
            type: "Frame",
            name: "CarouselViewport",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "100%",
              overflow: "hidden",
              borderRadius: "8px",
            },
            tailwindStyles: "w-full overflow-hidden rounded-lg",
            elements: [
              {
                type: "Frame",
                name: "CarouselTrack",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  overflowX: "auto",
                  scrollbarWidth: "none",
                  padding: "10px",
                  scrollSnapType: "x mandatory",
                },
                tailwindStyles: "flex overflow-x-auto scrollbar-hide p-2.5 snap-x snap-mandatory",
                elements: [
                  createTeamMemberHorizontal(
                    "Jane Doe",
                    "Product Designer",
                    "Jane has over 10 years of experience in UX design and loves creating intuitive interfaces.",
                    "",
                    [
                      { title: "LinkedIn", url: "https://linkedin.com", color: "blue-600" },
                      { title: "Twitter", url: "https://twitter.com", color: "blue-400" }
                    ]
                  ),
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "CarouselIndicators",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          justifyContent: "center",
          gap: "10px",
          marginTop: "30px",
        },
        tailwindStyles: "flex justify-center gap-2.5 mt-8",
        elements: [
          {
            type: "Frame",
            name: "Indicator",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "12px",
              height: "12px",
              borderRadius: "50%",
              backgroundColor: "#3b82f6",
            },
            tailwindStyles: "w-3 h-3 rounded-full bg-blue-500",
            elements: [],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Indicator",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "12px",
              height: "12px",
              borderRadius: "50%",
              backgroundColor: "#cbd5e1",
            },
            tailwindStyles: "w-3 h-3 rounded-full bg-slate-300",
            elements: [],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Indicator",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "12px",
              height: "12px",
              borderRadius: "50%",
              backgroundColor: "#cbd5e1",
            },
            tailwindStyles: "w-3 h-3 rounded-full bg-slate-300",
            elements: [],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "Indicator",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "12px",
              height: "12px",
              borderRadius: "50%",
              backgroundColor: "#cbd5e1",
            },
            tailwindStyles: "w-3 h-3 rounded-full bg-slate-300",
            elements: [],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Modern grid layout (max 4 per row)
export const teamMembersGrid: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembersGrid",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "60px 20px",
      backgroundColor: "#111827",
      color: "white",
    },
    tailwindStyles: "flex flex-col items-center w-full p-10 sm:p-14 bg-gray-900 text-white",
    elements: [
      {
        type: "Text",
        content: "Meet Our Experts",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "36px",
          color: "white",
          marginBottom: "15px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-3xl sm:text-4xl text-white mb-4 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "We are a team of passionate professionals dedicated to excellence",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#9ca3af",
          marginBottom: "50px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-gray-400 mb-12 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          width: "100%",
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
          gap: "30px",
          maxWidth: "1200px",
        },
        tailwindStyles: "w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 max-w-6xl",
        elements: [
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "100%",
                  paddingBottom: "100%", // Creates a perfect square
                  marginBottom: "20px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#8b5cf6",
                },
                tailwindStyles: "relative w-full pb-full mb-5 rounded-2xl overflow-hidden bg-purple-500",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      top: "0",
                      left: "0",
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "absolute inset-0 w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Michael Chen",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "22px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Chief Technology Officer",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#8b5cf6",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-purple-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "GitHub",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-purple-400",
                    href: "https://github.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "LinkedIn",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-purple-400",
                    href: "https://linkedin.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "100%",
                  paddingBottom: "100%", // Creates a perfect square
                  marginBottom: "20px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#ec4899",
                },
                tailwindStyles: "relative w-full pb-full mb-5 rounded-2xl overflow-hidden bg-pink-500",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      top: "0",
                      left: "0",
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "absolute inset-0 w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Olivia Davis",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "22px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Creative Director",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#ec4899",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-pink-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "Dribbble",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-pink-400",
                    href: "https://dribbble.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Instagram",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-pink-400",
                    href: "https://instagram.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "100%",
                  paddingBottom: "100%", // Creates a perfect square
                  marginBottom: "20px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#2563eb",
                },
                tailwindStyles: "relative w-full pb-full mb-5 rounded-2xl overflow-hidden bg-blue-600",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      top: "0",
                      left: "0",
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "absolute inset-0 w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "James Wilson",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "22px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Product Manager",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#3b82f6",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-blue-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "LinkedIn",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-blue-400",
                    href: "https://linkedin.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Twitter",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-blue-400",
                    href: "https://twitter.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "100%",
                  paddingBottom: "100%", // Creates a perfect square
                  marginBottom: "20px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#10b981",
                },
                tailwindStyles: "relative w-full pb-full mb-5 rounded-2xl overflow-hidden bg-emerald-500",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      position: "absolute",
                      top: "0",
                      left: "0",
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "absolute inset-0 w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Sophia Garcia",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "22px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "UX Researcher",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#10b981",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-emerald-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "Medium",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-emerald-400",
                    href: "https://medium.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "LinkedIn",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-emerald-400",
                    href: "https://linkedin.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

// Keep compatibility with the old exports
export const teamMembersComponent1: CustomComponent = teamMembersDynamicVertical;
export const teamMembersComponent2: CustomComponent = teamMembersDynamicHorizontal;
export const teamMembersComponent3: CustomComponent = teamMembersGrid;