import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const teamMembersComponent1: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembers1",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      gap: "20px",
      padding: "40px 20px",
    },
    tailwindStyles: "flex flex-col sm:flex-row justify-center gap-5 w-full p-10",
    elements: [
      {
        type: "Frame",
        name: "TeamMember",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          padding: "20px",
          backgroundColor: "#ffffff",
          borderRadius: "12px",
          boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
          width: "300px",
        },
        tailwindStyles: "flex flex-col items-center p-5 bg-white rounded-xl shadow-md w-full max-w-xs",
        elements: [
          {
            type: "Image",
            content: "Image",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "120px",
              height: "120px",
              borderRadius: "50%",
              objectFit: "cover",
              marginBottom: "15px",
              border: "2px dashed #ccc",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#aaa",
              backgroundColor: "#f9f9f9",
              fontSize: "14px",
              fontWeight: "bold",
            },
            tailwindStyles: "w-32 h-32 rounded-full object-cover mb-4 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Jane Doe",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontWeight: "bold",
              fontSize: "20px",
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "font-bold text-xl text-gray-800 mb-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Product Designer",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "16px",
              color: "#6d28d9",
              marginBottom: "15px",
            },
            tailwindStyles: "text-md text-purple-700 mb-4",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Jane has over 10 years of experience in UX design and loves creating intuitive interfaces.",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#666",
              textAlign: "center",
              marginBottom: "20px",
            },
            tailwindStyles: "text-sm text-gray-600 text-center mb-5",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "SocialLinks",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "row",
              gap: "15px",
            },
            tailwindStyles: "flex flex-row gap-4",
            elements: [
              {
                type: "Link",
                content: "LinkedIn",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#0077b5",
                  fontSize: "14px",
                },
                tailwindStyles: "text-blue-600 text-sm hover:underline",
                href: "https://linkedin.com",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "Twitter",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#1da1f2",
                  fontSize: "14px",
                },
                tailwindStyles: "text-blue-400 text-sm hover:underline",
                href: "https://twitter.com",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamMember",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          padding: "20px",
          backgroundColor: "#ffffff",
          borderRadius: "12px",
          boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
          width: "300px",
        },
        tailwindStyles: "flex flex-col items-center p-5 bg-white rounded-xl shadow-md w-full max-w-xs",
        elements: [
          {
            type: "Image",
            content: "Image",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              width: "120px",
              height: "120px",
              objectFit: "cover",
              marginBottom: "15px",
              border: "2px dashed #ccc",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#aaa",
              backgroundColor: "#f9f9f9",
              fontSize: "14px",
              fontWeight: "bold",
            },
            tailwindStyles: "w-32 h-32 object-cover mb-4 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "John Smith",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontWeight: "bold",
              fontSize: "20px",
              color: "#333",
              marginBottom: "5px",
            },
            tailwindStyles: "font-bold text-xl text-gray-800 mb-1",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "Lead Developer",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "16px",
              color: "#6d28d9",
              marginBottom: "15px",
            },
            tailwindStyles: "text-md text-purple-700 mb-4",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Text",
            content: "John is an experienced full-stack developer with expertise in modern web technologies.",
            id: uuidv4(),
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              fontSize: "14px",
              color: "#666",
              textAlign: "center",
              marginBottom: "20px",
            },
            tailwindStyles: "text-sm text-gray-600 text-center mb-5",
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "SocialLinks",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "row",
              gap: "15px",
            },
            tailwindStyles: "flex flex-row gap-4",
            elements: [
              {
                type: "Link",
                content: "LinkedIn",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#0077b5",
                  fontSize: "14px",
                },
                tailwindStyles: "text-blue-600 text-sm hover:underline",
                href: "https://linkedin.com",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Link",
                content: "GitHub",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  color: "#333",
                  fontSize: "14px",
                },
                tailwindStyles: "text-gray-800 text-sm hover:underline",
                href: "https://github.com",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const teamMembersComponent2: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembers2",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "40px 20px",
      backgroundColor: "#f8fafc",
    },
    tailwindStyles: "flex flex-col items-center w-full p-10 bg-slate-50",
    elements: [
      {
        type: "Text",
        content: "Our Team",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "32px",
          color: "#1e293b",
          marginBottom: "30px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-3xl text-slate-800 mb-8 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamGrid",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "20px",
          width: "100%",
          maxWidth: "1200px",
        },
        tailwindStyles: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 w-full max-w-6xl",
        elements: [
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              backgroundColor: "#ffffff",
              borderRadius: "8px",
              overflow: "hidden",
              boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
            },
            tailwindStyles: "flex flex-col bg-white rounded-lg overflow-hidden shadow-md",
            elements: [
              {
                type: "Frame",
                name: "MemberInfo",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  padding: "16px",
                  display: "flex",
                  flexDirection: "column",
                },
                tailwindStyles: "p-4 flex flex-col",
                elements: [
                  {
                    type: "Image",
                    content: "Image",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      width: "120px",
                      height: "120px",
                      objectFit: "cover",
                      marginBottom: "15px",
                      border: "2px dashed #ccc",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      color: "#aaa",
                      backgroundColor: "#f9f9f9",
                      fontSize: "14px",
                      fontWeight: "bold",
                    },
                    tailwindStyles: "w-32 h-32 object-cover mb-4 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "CEO & Founder",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "16px",
                      color: "#3b82f6",
                      marginBottom: "12px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-md text-blue-500 mb-3 font-medium",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Alex founded our company with a vision to transform the industry.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#64748b",
                      lineHeight: "1.5",
                      marginBottom: "16px",
                    },
                    tailwindStyles: "text-sm text-slate-500 leading-normal mb-4",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "SocialLinks",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "row",
                      gap: "8px",
                    },
                    tailwindStyles: "flex flex-row gap-2",
                    elements: [
                      {
                        type: "Link",
                        content: "Twitter",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "6px 10px",
                          backgroundColor: "#1da1f2",
                          color: "white",
                          borderRadius: "4px",
                          fontSize: "13px",
                        },
                        tailwindStyles: "px-3 py-1 bg-blue-400 text-white rounded text-sm",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "LinkedIn",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "6px 10px",
                          backgroundColor: "#0077b5",
                          color: "white",
                          borderRadius: "4px",
                          fontSize: "13px",
                        },
                        tailwindStyles: "px-3 py-1 bg-blue-700 text-white rounded text-sm",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              backgroundColor: "#ffffff",
              borderRadius: "8px",
              overflow: "hidden",
              boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
            },
            tailwindStyles: "flex flex-col bg-white rounded-lg overflow-hidden shadow-md",
            elements: [
              {
                type: "Image",
                content: "Image",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  width: "120px",
                  height: "120px",
                  objectFit: "cover",
                  marginBottom: "15px",
                  border: "2px dashed #ccc",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "#aaa",
                  backgroundColor: "#f9f9f9",
                  fontSize: "14px",
                  fontWeight: "bold",
                },
                tailwindStyles: "w-32 h-32 object-cover mb-4 border-2 border-dashed border-gray-300 flex items-center justify-center text-gray-400 bg-gray-100",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "MemberInfo",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  padding: "16px",
                  display: "flex",
                  flexDirection: "column",
                },
                tailwindStyles: "p-4 flex flex-col",
                elements: [
                  {
                    type: "Text",
                    content: "Sarah Williams",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontWeight: "bold",
                      fontSize: "20px",
                      color: "#334155",
                      marginBottom: "4px",
                    },
                    tailwindStyles: "font-bold text-xl text-slate-700 mb-1",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Marketing Director",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "16px",
                      color: "#3b82f6",
                      marginBottom: "12px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-md text-blue-500 mb-3 font-medium",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Text",
                    content: "Sarah leads our marketing efforts with creative campaigns.",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      fontSize: "14px",
                      color: "#64748b",
                      lineHeight: "1.5",
                      marginBottom: "16px",
                    },
                    tailwindStyles: "text-sm text-slate-500 leading-normal mb-4",
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Frame",
                    name: "SocialLinks",
                    id: uuidv4(),
                    content: "",
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      display: "flex",
                      flexDirection: "row",
                      gap: "8px",
                    },
                    tailwindStyles: "flex flex-row gap-2",
                    elements: [
                      {
                        type: "Link",
                        content: "Twitter",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "6px 10px",
                          backgroundColor: "#1da1f2",
                          color: "white",
                          borderRadius: "4px",
                          fontSize: "13px",
                        },
                        tailwindStyles: "px-3 py-1 bg-blue-400 text-white rounded text-sm",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                      {
                        type: "Link",
                        content: "LinkedIn",
                        id: uuidv4(),
                        isSelected: false,
                        x: 0,
                        y: 0,
                        styles: {
                          padding: "6px 10px",
                          backgroundColor: "#0077b5",
                          color: "white",
                          borderRadius: "4px",
                          fontSize: "13px",
                        },
                        tailwindStyles: "px-3 py-1 bg-blue-700 text-white rounded text-sm",
                        href: "#",
                        src: "",
                        parentId: "",
                        projectId: "",
                      },
                    ],
                    href: "",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};

export const teamMembersComponent3: CustomComponent = {
  component: {
    type: "Frame",
    name: "TeamMembers3",
    id: uuidv4(),
    content: "",
    isSelected: false,
    x: 0,
    y: 0,
    styles: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "60px 20px",
      backgroundColor: "#111827",
      color: "white",
    },
    tailwindStyles: "flex flex-col items-center w-full p-14 bg-gray-900 text-white",
    elements: [
      {
        type: "Text",
        content: "Meet Our Experts",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontWeight: "bold",
          fontSize: "42px",
          color: "white",
          marginBottom: "15px",
          textAlign: "center",
        },
        tailwindStyles: "font-bold text-5xl text-white mb-4 text-center",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Text",
        content: "We are a team of passionate professionals dedicated to excellence",
        id: uuidv4(),
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          fontSize: "18px",
          color: "#9ca3af",
          marginBottom: "50px",
          textAlign: "center",
          maxWidth: "700px",
        },
        tailwindStyles: "text-lg text-gray-400 mb-12 text-center max-w-2xl",
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
      {
        type: "Frame",
        name: "TeamContainer",
        id: uuidv4(),
        content: "",
        isSelected: false,
        x: 0,
        y: 0,
        styles: {
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          flexWrap: "wrap",
          gap: "40px",
          width: "100%",
          maxWidth: "1200px",
        },
        tailwindStyles: "flex flex-wrap justify-center gap-10 w-full max-w-6xl",
        elements: [
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              width: "280px",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center w-64 relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "220px",
                  height: "220px",
                  marginBottom: "25px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#8b5cf6",
                },
                tailwindStyles: "relative w-56 h-56 mb-6 rounded-2xl overflow-hidden bg-purple-500",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Michael Chen",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "24px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-2xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Chief Technology Officer",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#8b5cf6",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-purple-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "GitHub",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-purple-400",
                    href: "https://github.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "LinkedIn",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-purple-400",
                    href: "https://linkedin.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Twitter",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-purple-400",
                    href: "https://twitter.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
          {
            type: "Frame",
            name: "TeamMember",
            id: uuidv4(),
            content: "",
            isSelected: false,
            x: 0,
            y: 0,
            styles: {
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              width: "280px",
              position: "relative",
            },
            tailwindStyles: "flex flex-col items-center w-64 relative group",
            elements: [
              {
                type: "Frame",
                name: "ImageContainer",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  position: "relative",
                  width: "220px",
                  height: "220px",
                  marginBottom: "25px",
                  borderRadius: "16px",
                  overflow: "hidden",
                  backgroundColor: "#ec4899",
                },
                tailwindStyles: "relative w-56 h-56 mb-6 rounded-2xl overflow-hidden bg-pink-500",
                elements: [
                  {
                    type: "Image",
                    content: "",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      mixBlendMode: "luminosity",
                      opacity: "0.8",
                      transition: "all 0.3s ease",
                    },
                    tailwindStyles: "w-full h-full object-cover mix-blend-luminosity opacity-80 group-hover:opacity-100 transition-all duration-300",
                    href: "",
                    src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Olivia Davis",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontWeight: "bold",
                  fontSize: "24px",
                  color: "white",
                  marginBottom: "5px",
                },
                tailwindStyles: "font-bold text-2xl text-white mb-1",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Text",
                content: "Creative Director",
                id: uuidv4(),
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  fontSize: "16px",
                  color: "#ec4899",
                  marginBottom: "12px",
                  fontWeight: "500",
                },
                tailwindStyles: "text-md text-pink-500 mb-3 font-medium",
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
              {
                type: "Frame",
                name: "SocialLinks",
                id: uuidv4(),
                content: "",
                isSelected: false,
                x: 0,
                y: 0,
                styles: {
                  display: "flex",
                  flexDirection: "row",
                  gap: "15px",
                },
                tailwindStyles: "flex flex-row gap-4",
                elements: [
                  {
                    type: "Link",
                    content: "Dribbble",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-pink-400",
                    href: "https://dribbble.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "Instagram",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-pink-400",
                    href: "https://instagram.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                  {
                    type: "Link",
                    content: "LinkedIn",
                    id: uuidv4(),
                    isSelected: false,
                    x: 0,
                    y: 0,
                    styles: {
                      color: "#d1d5db",
                      fontSize: "14px",
                      fontWeight: "500",
                    },
                    tailwindStyles: "text-gray-300 text-sm font-medium hover:text-pink-400",
                    href: "https://linkedin.com",
                    src: "",
                    parentId: "",
                    projectId: "",
                  },
                ],
                href: "",
                src: "",
                parentId: "",
                projectId: "",
              },
            ],
            href: "",
            src: "",
            parentId: "",
            projectId: "",
          },
        ],
        href: "",
        src: "",
        parentId: "",
        projectId: "",
      },
    ],
    href: "",
    src: "",
    parentId: "",
    projectId: "",
  },
};